In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv('SMSSpamCollection',sep='\t',names=['label','message'])

In [3]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
## BOW , TFIDF , CLASSIFICATION BY ML ALGO

***Data Cleaning & Preprocessing***

In [5]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [7]:
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'update_now xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

***Create Bag Of Words***

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
## binary BOW
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [10]:
X=cv.fit_transform(corpus).toarray()
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter =dict(float=lambda x:"%.3g" % x))

In [11]:
X # independent feature

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], shape=(5572, 2500))

In [12]:
## output features
y=pd.get_dummies(messages['label'])

In [13]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [14]:
y=y.iloc[:,0].values

In [15]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True], shape=(5572,))

In [16]:
y=y.astype(int)

In [17]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], shape=(5572,))

***Dataset Spliting***

In [18]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [19]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [20]:
y_pred=spam_detect_model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score,classification_report

In [22]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9820627802690582

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93       150
           1       0.98      0.99      0.99       965

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

***By using TF-IDF***

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X=tfidf.fit_transform(corpus).toarray()

In [25]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [26]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [27]:
y_pred=spam_detect_model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,classification_report

In [29]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9811659192825112

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.87      0.93       152
           1       0.98      1.00      0.99       963

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.96      1115
weighted avg       0.98      0.98      0.98      1115

## ⚠️ Preventing Data Leakage

Initially, it may seem natural to perform **Bag of Words (BoW)** or **TF-IDF** on the entire dataset before splitting it into training and testing sets. However, this introduces **data leakage**.

### Why is this a problem?

BoW and TF-IDF learn the vocabulary and word statistics (such as document frequencies in TF-IDF) from the data they are fitted on. If they are fitted on the **entire dataset**, information from the **test set** is indirectly used during training.

As a result, the model gets access to information that would not be available in a real-world scenario, leading to overly optimistic evaluation results.

### ✅ Correct Workflow

1. **Preprocessing and Cleaning**
2. **Train-Test Split**
3. **Fit BoW/TF-IDF on the Training Data only**
4. **Transform both Training and Test Data using the fitted vectorizer**
5. **Train the Machine Learning Model**
6. **Evaluate on the Test Set**

1. Preprocessed and Cleaned

In [31]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'update_now xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

2. Train Test Split

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [33]:
X_train

['hi think match',
 'noth ok anyway give treat',
 'daddi take good care',
 'get ten billion call text help god',
 'guy browsin compulsori',
 'ask say pleas messag',
 'wait call',
 'dear u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr',
 'white fudg oreo store',
 'ok thk got u wan come wat',
 'wish u mani mani return day happi birthday vikki',
 'ball move lot spin last difficult bat',
 'know lt gt around',
 'v fan',
 'wat r u',
 'spoil bed well',
 'think need go late school night especi one class one miss last wednesday probabl fail test friday',
 'sore throat scratch talk',
 'free call pa',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'ah well confus thing',
 'good need receipt well done ye pleas tell number could ring',
 'freemsg claim ur sm messag text ok use web mobil ur mate etc join txt com p wk c box la wu remov txtx stop',
 'teach app da come colleg',
 'even friend priest call',
 'haha mayb u rite u know well da feel like someon gd lor u faster go find one gal group attach liao',
 'love smell bu tobacco',
 'dont know oh hope month',
 'agre stop thinkin ipad pleas ask macho question',
 'mro come gym machan goodnight',
 'bore housew chat n date bt nation rate p min landlin',
 'k call close',
 'urgent import inform user today lucki day find log onto http www urawinn com fantast surpris await',
 'free entri gr prize wkli comp chanc win latest nokia psp cash everi wk txt great http www gr prize com',
 'ran younger man make pretti babi togeth',
 'wont anyth de',
 'probabl earlier station think',
 'oh icic k lor den meet day',
 'sen told go join uncl financ cbe',
 'leav wif lar wan carri meh heavi da num familiar',
 'u dun drive go sch',
 'great run ttyl',
 'say hi get ass back south tampa prefer kegger',
 'good night dear sleepwel amp take care',
 'chile pleas lt decim gt hour drive come time sublet feb april audit season',
 'tell need investig anywher',
 'good morn princess',
 'heard u call night knicker make beg like u last time xx luv nikiyu net',
 'urgent mobil number award bonu caller prize call land line valid hr',
 'sad stori man last week b day wife nt wish parent forgot n kid went work even colleagu wish',
 'tund wish great day abiola',
 'lol would awesom payback',
 'promis take good care princess run pleas send pic get chanc ttyl',
 'want new video phone anytim network min text five pound per week call repli deliveri tomorrow',
 'probabl money worri thing come due sever outstand invoic work two three month ago',
 'back lemm know readi',
 'hey sexi bun day word morn ym think',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'ye possibl dint tri pl dont tell one k',
 'mum say wan go go shun bian watch da glass exhibit',
 'tell femal v throw decid get',
 'fyi take quick shower epsilon like lt gt min',
 'sorri lot friend friend stuff talk actual guy want buy',
 'miss ya need ya want ya love ya',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'sorri mail',
 'onlin transact',
 'take care financi problem help',
 'ew one',
 'problem spend lot qualiti time togeth',
 'new year plan',
 'mmm fuck merri christma',
 'u go phone gonna die stay',
 'baaaaaaaab wake miss crave need',
 'yeh indian nice tho kane bit shud go drink sometim soon mite hav go da work laugh soon love pete x x',
 'one day billion class right',
 'yep fine ice age',
 'help propos go back tomorrow',
 'ha u ju ate honey ar sweet',
 'hi babe im home wanna someth xx',
 'call da wait call',
 'hi darlin kate u doin somethin tonight im go pub call swan someth parent one drink phone u',
 'k yan jiu liao sat go bugi vill one frm den hop parco nb sun go cine frm den hop orc mrt hip hop',
 'pleas call custom servic repres pm guarante cash prize',
 'da bu go home',
 'dear deni word pleas',
 'left dessert u wan go suntec look u',
 'mom want know',
 'cal sir meet',
 'k u bore come home',
 'carlo say mu lt gt minut',
 'wake gt',
 'tf p',
 'ye good crickit mind',
 'answerin phone actual pretti reason hour sleepi',
 'laptop noe infra slow lar wan fast one',
 'great trip india bring light everyon project everyon lucki see smile bye abiola',
 'lover need',
 'object bf come',
 'hmmm give one day',
 'dont kick coco',
 'send logo ur lover name join heart txt love name name mobno eg love adam eve yahoo pobox w wq txtno ad p',
 'know grumpi old peopl mom like better lie alway one play joke',
 'sorri call later',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'go good problem still need littl experi understand american custom voic',
 'hope feel great pl fill abiola',
 'spook mob halloween collect logo pic messag plu free eeri tone txt card spook zed p per logo pic',
 'say quit least time day wudn take much notic nah mind gonna see want come taunton tonight u tell',
 'want lick pussi',
 'prabha soryda reali frm heart sori',
 'k k tomorrow onward start ah',
 'home watch tv lor',
 'got meh',
 'hey miss tm last night phone charg smile meet friend shortli',
 'k sent',
 'understand loss gain work school',
 'hi babi ive got back work want see u allday hope didnt piss u phone today u give call xxx',
 'pleas send aunti number',
 'shhhhh nobodi suppos know',
 'win newest harri potter order phoenix book repli harri answer question chanc first among reader',
 'woke yeesh late fall asleep til lt gt',
 'make easi pay back lt gt yr say pay back earlier get',
 'lol tri make day littl interest',
 'think u wrong number',
 'great new offer doubl min doubl txt best orang tariff get latest camera phone free call mobileupd free stoptxt cs',
 'luck catch put',
 'urgent pleas call landlin abta complimentari tenerif holiday cash await collect sae cs box cw wx ppm',
 'regist optin subscrib ur draw gift voucher enter receipt correct an what bbc chart',
 'troubl class go well due dodgey one expect mine tomo see recoveri time place',
 'hey rite u put evey mnth',
 'take half day leav bec well',
 'length e e top shorter n got fring thk go liao lazi dun wan distract u also',
 'join today',
 'would ip address test consid comput minecraft server',
 'nope meanwhil talk say make greet',
 'u free sat rite u wan watch infern affair wif n darren n mayb xy',
 'pleas give us connect today lt decim gt refund bill',
 'said kiss kiss sound effect gorgeou man kind person need smile brighten day',
 'today voda number end select receiv award hava match pleas call quot claim code standard rate app',
 'privat account statement show un redeem point call identifi code expir',
 'hey congrat u id luv ive go home',
 'talk atleast day otherwis miss best friend world shakespear shesil lt gt',
 'fun fact although would think armand would eventu build toler shit consid much smoke get fuck like hit',
 'get back time soon',
 'jolli good way give u ticket sat eve speak x',
 'right meanwhil project twin comin',
 'thing quick question',
 'pl send compani name saibaba colani',
 'got ga money chanc gang want go grand natur adventur',
 'thinkin someon good drug',
 'yavnt tri yet never play origin either',
 'peopl see msg think iam addict msging wrong bcoz don\\ know iam addict sweet friend bslvyl',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'finish work yet',
 'yup alreadi thanx print n hand',
 'u reckon need arrang transport u thank',
 'way go back',
 'ye dont care need bad princess',
 'ring come guy costum gift futur yowif hint hint',
 'forgot work today wanna chat thing ok drop text free bore etc ring hope well nose essay xx',
 'ya nice readi thursday',
 'hey leav friday wait ask superior tell',
 'work ring u thing whole hous scream brat pull hair love u',
 'take small dose tablet fever',
 'marri local women look discreet action real match instantli phone text match msg cost p stop txt stop bcmsfwc n xx',
 'hello drivbi quit edrunk sorri iff pthi make senrd dnot ^ dancc drum n basq ihav fun nhite x ro xxxxxxx',
 'hello u u u b move flat co need arrang pick lamp etc take care hello carolin',
 'u r much close heart u go away shatter plz stay',
 'place want da',
 'workin get job',
 'engalnd telli decid let watch mia elliot kiss damn',
 'wait come lt gt min',
 'xma reward wait comput randomli pick loyal mobil custom receiv reward call',
 'pl pl drink plenti plenti water',
 'pride almost lt gt year old takin money kid suppos deal stuff grownup stuff tell',
 'usual take fifteen fuck minut respond ye question',
 'told return order',
 'love know feel make belli warm wish love shall meet dream ahmad ador kiss',
 'remind download content alreadi paid goto http doit mymobi tv collect content',
 'aight rush ask jay',
 'hey sat go intro pilat kickbox',
 'arr birthday today wish get oscar',
 'repli win weekli profession sport tiger wood play send stop end servic',
 'urgent nd attempt contact u u call b csbcm wc n xx callcost ppmmobilesvari max',
 'yo howz u girl never rang india l',
 'wish great semest',
 'happen tell truth',
 'would like see xxx pic hot nearli ban uk',
 'oh thkin goin yogasana den nd go den rush parco nb oki lor u call readi',
 'sleep nt feel well',
 'studi free next weekend',
 'crazi ar marri like gd look guy fren like say korean leona fave dun thk aft think mayb prob go',
 'valentin game send di msg ur friend answer r someon realli love u que colour suit best',
 'k k perform',
 'babe got enough money pick bread milk give back get home',
 'actual decid hungri left yet v',
 'review keep fantast nokia n gage game deck club nokia go www cnupdat com newslett unsubscrib alert repli word',
 'speak cash yet',
 'bank say money',
 'practis curtsey',
 'yun ah ubi one say wan call tomorrow call look iren ere got bu ubi cre ubi tech park ph st wkg day n',
 'free camera phone linerent month cross ntwk min price txt bundl deal also avbl call call optout j mf',
 'u nokia plu free digit camera u get u win free auction take part send nokia pobox tcr w',
 'yup free',
 'free st week nokia tone ur mobil everi week txt nokia get txting tell ur mate www getz co uk pobox w wq norm p tone',
 'shore takin bu',
 'yeah imma come caus jay want drug',
 'dunno ju say go lido time',
 'know wot peopl wear shirt jumper hat belt know r cribb',
 'alway put busi put pictur ass facebook one open peopl ever met would think pictur room would hurt make feel violat',
 'thanx',
 'raji pl favour pl convey birthday wish nimya pl today birthday',
 'alright hook guy',
 'movi theatr go watch unlimit movi pay',
 'place man',
 'pleas dont say like hi hi hi',
 'raji pl favour pl convey birthday wish nimya pl today birthday',
 'boltblu tone p repli poli mono eg poli cha cha slide yeah slow jamz toxic come stop tone txt',
 'lor ya go dinner togeth',
 'jesu armand realli tri tell everybodi find',
 'tri get lost fact tee hee',
 'normal',
 'g class earli tomorrow thu tri smoke lt gt',
 'kothi print marandratha',
 'eatin later eatin wif fren lei go home first',
 'gran onlyfound afew day ago cusoon honi',
 'sorri call later',
 'yo around got car back',
 'put stuff road keep get slipperi',
 'k k sm chat',
 'get ur st rington free repli msg tone gr top tone phone everi week per wk opt send stop',
 'alreadi one guy love',
 'hi hun im comin nite tell everi im sorri hope u ava goodtim oli rang melnit ifink mite b sort il explain everythin mon l rs x',
 'much fight good nite',
 'frnd juz word mere relationship silent promis say wherevr whenevr forevr gudnyt dear',
 'hey darlin pick u colleg u tell wen mt love pete xx',
 'lol real told dad cancer',
 'watch live',
 'ladi first genu second k',
 'mobil mth updat free orang latest colour camera mobil unlimit weekend call call mobil upd freefon stoptx',
 'see film',
 'know mood today',
 'ever easier',
 'gonna blake night might abl get littl earli',
 'big brother alert comput select u k cash voucher call ntt po box cro bt landlin cost ppm mobil vari',
 'freemsg fanci flirt repli date join uk fastest grow mobil date servic msg rcvd p optout txt stop repli date',
 'sent jd custom servic cum account execut ur mail id detail contact us',
 'think wast rr',
 'hi keen go kind feel go tomo mind',
 'hope good week check',
 'mayb say hi find got card great escap wetherspoon',
 'good regist vote',
 'exhaust train morn much wine pie sleep well',
 'easi ah sen got select mean good',
 'dunno lei shd b drive lor co go sch hr oni',
 'cool lt gt inch long hope like big',
 'alright make sure car back tonight',
 'great escap fanci bridg need lager see tomo',
 'sorri call later',
 'pizza u want',
 'account credit free text messag activ txt word credit cs www biz',
 'tri neva mate',
 'come u got noth',
 'da happi sit togeth na',
 'sorri meet call later',
 'think ask gym excus lazi peopl jog',
 'privat account statement show un redeem point call identifi code expir',
 'havent add yet right',
 'happen yo date',
 'alway celebr ny famili',
 'sometim heart remembr someon much forget someon soon bcoz heart like everyon like one rememb everytim bslvyl',
 'aiyar dun disturb u liao thk u lot aft ur cupboard come',
 'thank rington order ref number k mobil charg tone arriv pleas call custom servic',
 'famili respond anyth room went home diwali one call come make feel like die',
 'thank u better work caus feel use otherwis',
 'ok set let u noe e detail later',
 'storm msg wen u lift phne u say hello u knw wt real mean hello name girl ye u knw dat girl margaret hello girlfrnd f grahmbel invnt telphon moral one get name person bt girlfrnd g n g h',
 'haha awesom might need take doin tonight',
 'lol could starv lose pound end day',
 'huh mean comput scienc like dat one push n',
 'finish miss plenti',
 'much blackberri bold nigeria',
 'drama pl enough famili struggl hot sun strang place reason ego go invit actual necess go wait seriou reppurcuss',
 'okey dokey swashbuckl stuff oh',
 'kalli readi bat nd inning',
 'k k detail want transfer acc enough',
 'esplanad lor els',
 'wrong phone phone answer one assum peopl well',
 'plan pongal',
 'langport sorri probabl bed pm suck ill xma go sri lanka',
 'sm servic inclus text credit pl gotto www comuk net login qxj unsubscrib stop extra charg help comuk cm ae',
 'hey r still onlin finish format',
 'like italian food',
 'studi alon without anyon help cant need studi',
 'hi alway onlin yahoo would like chat someday',
 'im done studyn librari',
 'though shd go n fun bar town someth sound ok',
 'knew u slept v late yest wake late',
 'siva hostel aha',
 'olol print forum post guy exact prob fix gpu replac hope dont ignor',
 'dunno lei neva say',
 'probabl come everybodi done around lt gt right',
 'happen interview',
 'dude sux snake got old raiden got buff',
 'hi email address chang',
 'freemsg hi babi wow got new cam mobi wanna c hot pic fanci chat im w utxt rpli chat hlp msg p rcv',
 'u awak snow',
 'babe answer see mayb better reboot ym got photo great',
 'mmm yummi babe nice jolt suzi',
 'ye princess want pleas everi night wish command',
 'done mean',
 'long quit get like minut day',
 'aight time want come',
 'thank honey still heard anyth leav bit longer crowd tri later great advic thank hope cardiff still',
 'feb lt gt love u day send di ur valu frnd evn come back u gt marri person u luv u ignor di u lose ur luv evr',
 'er yeah b sorri tell pub cafe sit come wen u',
 'home way',
 'jst chang tat',
 'playin space poker u',
 'see see mayb reboot ym seen buzz',
 'okay go sleep later',
 'work week',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 'money money aint thing sha',
 'love cuddl want hold strong arm right',
 'let snow let snow kind weather bring ppl togeth friendship grow',
 'get garden readi summer free select summer bulb seed worth scotsman saturday stop go notxt co uk',
 'directli behind abt row behind',
 'pleas leav topic sorri tell',
 'hello per request lt gt rs transfer',
 'hey sexi bun told ador loverboy hope rememb thank sister law meatbal grin love babe',
 'get anywher damn job hunt',
 'da vijay go talk jaya tv',
 'way home went chang batt watch go shop bit lor',
 'haha kid papa need drug',
 'offic call lt gt min',
 'joy father john john ____ joy father u an th hav lt gt iq ti ia question tri answer',
 'get class bsn like lt gt minut know advis',
 'escap theatr go watch kavalan minut',
 'much get',
 'freemsg feelin kinda lnli hope u like keep compani jst got cam mobi wanna c pic txt repli date msg p rcv hlp stop',
 'nt goin got somethin unless meetin dinner lor haha wonder go ti time',
 'nd time tri contact u u pound prize claim easi call p per min bt nation rate',
 'prize go anoth custom c www c biz p min polo ltd suit london w j hl pleas call back busi',
 'take phone callon friday assum year',
 'ok also wan watch e pm show',
 'sday join train start today',
 'k give back thank',
 'mmmmmm love much ahmad wait year begin everi second take closer side happi new year love',
 'nd time tri contact u u prize claim easi call p per minut bt nation rate',
 'time come tomorrow',
 'win newest harri potter order phoenix book repli harri answer question chanc first among reader',
 'what come hill monster hope great day thing r go fine busi though',
 'check room befor activ',
 'pleas call immedi urgent messag wait',
 'yup give problem mayb ju leav',
 'ok lor',
 'still game',
 'actual mobil full msg work onlin need send lt gt sent msg wil explain u later',
 'think disturb da',
 'hi engag fixd lt gt th next month know realli shock bt hmm njan vilikkam ws al sudn',
 'chanc realiti fantasi show call p per min ntt ltd po box croydon cr wb nation rate call',
 'u secret admir look make contact u find r reveal think ur special call',
 'match start india lt gt',
 'love want flood pretti pussi cum',
 'hi harish rent transfr ur acnt',
 'ur physic get',
 'meanwhil shit suit xavier decid give us lt gt second warn samantha come play jay guitar impress shit also think doug realiz live anymor',
 'k eng rock ash',
 'hi ya babe x u goten bout scammer get smart though regular vodafon respond get prem rate msg subscript no use also bewar',
 'costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min',
 'forward hi mailbox messag sm alert messag match pleas call back retriev messag match',
 'india go draw seri mani year south african soil',
 'beauti truth express face could seen everyon depress heart could understood love one gud ni',
 'ow u dey paid thousad told u would call',
 'one issu california okay snow manag',
 'hey look like wrong one kappa guy number still phone want text see around',
 'bday real april',
 'prakesh know',
 'avail like right around hillsborough amp lt gt th',
 'oh wow that gay firmwar updat help',
 'someon u know ask date servic contact cant guess call reveal pobox xy p',
 'ok thanx',
 'morn ok',
 'outsid island head toward hard rock run',
 'look like u wil b get headstart im leav bout ish u r desper compani could head earlier goin meet rummer',
 'reach ur home lt gt minut',
 'perform award calcul everi two month current one month period',
 'friendship poem dear dear u r near hear dont get fear live cheer tear u r alway dear gud ni',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'lol knew saw dollar store',
 'cant pick phone right pl send messag',
 'releas vday shirt u put make bottom half nake instead white underwear',
 'thought could go dinner treat seem ok',
 'ee msg na poortiyagi odalebeku hanumanji name hanuman bajarangabali maruti pavanaputra sankatmochan ramaduth mahav ee name lt gt janarig ivatt kalisidar next saturday olag ondu good news keluviri maretar ind dodda problum nalli siguviri idu matra lt gt true neglet',
 'ask keep one mayb get messag sent glo',
 'urgent nd attempt contact u prize yesterday still await collect claim call',
 'u subscrib best mobil content servic uk per ten day send stop helplin',
 'hey someth came last min think wun sign tmr hee',

In [34]:
X_test

['geeee miss alreadi know think fuck wait till next year togeth love kiss',
 'win urgent mobil number award prize guarante call land line claim valid hr ppm',
 'unsubscrib servic get ton sexi babe hunk straight phone go http gotbab co uk subscript',
 'yup msg tat yiju tot group mate co meet today mah askin leav earlier wat mah co mayb haf walk v far',
 'lick everi drop readi use mouth well',
 'beauti life next second hide thousand secret wish everi second wonder ur life gud n',
 'meet call later',
 'mean websit ye',
 'ok wun b angri msg u aft come home tonight',
 'alright good night',
 'xma new year eve ticket sale club day till pm thur fri sat night week sell fast',
 'call messag miss call',
 'winner special select receiv cash award speak live oper claim call pm cost p',
 'might come kerala day prepar take leav finalis dont plan travel visit need finish urgent work',
 'dad back ph',
 'goodmorn today late lt decim gt min',
 'come get b quit diff guess rite',
 'winner guarante caller prize final attempt contact claim call ppmpobox bhamb xe',
 'haha think',
 'geniu brother pl send number skype',
 'meant say cant wait see u get bore bridgwat banter',
 'need say anyth know outsid',
 'time fix spell sometim get complet diff word go figur',
 'lol differ go tri find everi real life photo ever took',
 'dont talk ever ok word',
 'hungri',
 'reckon need town eightish walk carpark',
 'cant u tri new invent fli joke',
 'went ur hon lab one',
 'much gave morn',
 'hmm bad news hype park plaza studio taken left bedrm',
 'yo dude guess got arrest day',
 'tell shola pleas go colleg medicin visit academ depart tell academ secretari current situat ask transfer ask someon check sagamu thing lautech vital complet medic educ nigeria less expens much less expens unless get citizen rate new zealand',
 'spoon okay',
 'lul im gettin juici gossip hospit two nurs talk fat gettin one think she obes oyea',
 'dear chechi talk',
 'tell friend come round til like lt gt ish',
 'good even ttyl',
 'would still cozi exhaust last night nobodi went school work everyth close',
 'tall princess',
 'sweet well princess pleas tell like dislik bed',
 'shall fine avalarr hollalat',
 'regret inform u nh made mistak u never actual born pleas report yor local hospit b termin r sorri inconveni',
 'ok',
 'mmmm cant wait lick',
 'ok lor town lei',
 'realli get hang around',
 'someon u know ask date servic contact cant guess call reveal po box wu',
 'actual wait week start put ad',
 'alright bring see like lt gt min',
 'think u x',
 'nah im goin wrk j wot bout u',
 'rememb',
 'hey gorgeou man work mobil number good one babe squishi mwah',
 'tunji queen wish great day abiola',
 'u made appoint',
 'pl accept one day beg chang number',
 'orang custom may claim free camera phone upgrad loyalti call offer end thmarch c appli opt availa',
 'u come back dinner rite dad ask confirm wif u',
 'pop lt gt ibuprofen help',
 'fuck babe miss sooooo much wish sleep bed lone go sleep dream love',
 'start dont stop pray good idea anyth see help guy forward link',
 'good afternoon love goe day sleep hope well boytoy think',
 'sir wait mail',
 'huh hyde park mel ah opp got confus anyway tt e best choic den juz take',
 'hi petey noi ok want chat coz avent spoken u long time hope ur doin alrit good nit js love ya x',
 'compliment away system side',
 'oh brand',
 'slaaaaav must summon time wish come anymor',
 'nan sonathaya soladha boss',
 'nope sinc ayo travel forgotten guy',
 'pen thing beyond joke wont biro master ever',
 'wan win meet greet westlif u current tour unbreak untam unkempt text cost p std text',
 'good afternoon starshin boytoy crave yet ach fuck sip cappuccino miss babe teas kiss',
 'press confer da',
 'said would woke',
 'alreadi got flaki parent snot suppos child job support parent ride age anyway suppos support hurt unintent hurt nonetheless',
 'nah dub je still buff',
 'number gonna massiv pain ass rather get involv possibl',
 'ye last week take live call',
 'probabl still go stuff',
 'happi new year dear brother realli miss got number decid send text wish happi abiola',
 'e admin build might b slightli earlier call u reach',
 'pathaya enketa maraikara pa',
 'yeah leav hour least sound',
 'hiya u pay money account thank got pleasant surpris check balanc u c get statement acc',
 'k k cant come search job',
 'met stranger choos friend long world stand friendship never end let friend forev gud nitz',
 'keep see weird shit bein woah realis actual reason oh',
 'u think girl propos u today se ur bloodi funki shit fuck face asssssholeee',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'super da good replac murali',
 'oh gei happend tron mayb ill dl',
 'anyth lar',
 'okay name ur price long legal wen pick u ave x am xx',
 'ya take ure practic lesson start june',
 'come ur home',
 'mth half price orang line rental latest camera phone free phone mth call mobilesdirect free updat stoptxt',
 'mila age blond new uk look sex uk guy u like fun text mtalk pp txt st free increment help',
 'good afternoon sexi bun goe job search wake first thought alway love wish fine happi know ador',
 'sorri meet call later',
 'privat account statement show un redeem point call identifi code expir',
 'guarante award even cashto claim ur award call free stop getstop php rg jx',
 'want see pretti pussi',
 'keep payasam rinu bring',
 'wonder other took',
 'tri reach without success',
 'hey project start aha da',
 'aathi dear',
 'suppos meet discuss abt trip thought xuhui told afternoon thought go lesson',
 'happi new year u ur famili may new year bring happi stabil tranquil ur vibrant colour life',
 'u dun say earli hor u c alreadi say',
 'life never much fun great came made truli special forget enjoy one gbp sm',
 'spoke uncl john today strongli feel need sacrific keep go call beg listen dont make promis make clear thing easi need pleas let us work thing long keep expect help creativ stifl pl keep happi promis part',
 'babe love cover face kiss',
 'urgent pleas call abta complimentari spanish holiday cash await collect sae cs box po ez ppm',
 'eeri nokia tone u rpli tone titl eg tone dracula titl ghost addamsfa munster exorcist twilight www getz co uk pobox w wq p',
 'school start stay weather like food social support system like friend school thing import',
 'e best ur drive tmr',
 'dear u invit xchat final attempt contact u txt chat',
 'yeah right bring tape measur fri',
 'say somebodi name tampa',
 'either way work lt gt year old hope doesnt bother',
 'news hassl get weed week andr money haughaighgtujhyguj',
 'sorri call later',
 'uncl boy need movi oh guid plu know torrent particularli legal system slow gr day plu start co dont meet onlin honey moon',
 'read gud habit nan bari hudgi yorg pataistha ertini kano',
 'home alway chat',
 'ummmmmaah mani mani happi return day dear sweet heart happi birthday dear',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'sorri chikku cell got problem tht nt abl repli u msg u',
 'wish great day moji told offer alway speechless offer easili go great length behalf stun exam next friday keep touch sorri',
 'lol right diet everyday cheat anyway meant fatti',
 'pay attent',
 'weather',
 'way offic da',
 'go ok na',
 'reach alreadi',
 'keep away like',
 'bit ur smile hppnss drop ur tear sorrow part ur heart life heart like mine wil care u forevr goodfriend',
 'dear good morn feel dear',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'romant pari night flight book next year call ts cs appli',
 'call tell u call claim prize u enter ur mobil person detail prompt care',
 'like lt gt question',
 'say bold torch later one torch bold',
 'hey realli pretti late want go lesson first join reach tp mrt',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'ye babi studi posit kama sutra',
 'got lousi sleep kept wake everi hour see cat want come worri cold',
 'gud gud k chikku tke care sleep well gud nyt',
 'thought see',
 'lol ok rememb til last nite',
 'ho ho big belli laugh see ya tomo',
 'plm come da way',
 'look forward sex cuddl two sleep',
 'date two start sent text talk sport radio last week connect think coincid',
 'solv case man found murder lt decim gt lt gt afternoon wife call polic polic question everyon wife sir sleep murder took place cook cook garden pick veget hous maid went post offic children went play neighbour went marriag polic arrest murder immedi repli reason u r brilliant',
 'free msg rington http tm widel com index wml id b ecef ff first true jul',
 'dude u knw also telugu tht gud k gud nyt',
 'oh kay sat right',
 'suck got plan yo valentin yo valentin',
 'want snow freez windi',
 'lol would mom would fit tell whole famili crazi terribl',
 'free messag thank use auction subscript servic p msgrcvd skip auction txt unsubscrib txt stop customercar',
 'thx well month',
 'lol know hey someon great inperson flea forum love',
 'moji love word rich day',
 'da what plan',
 'argh g spotti anyway thing rememb research provinc sterl problem free place look',
 'alex say ok ok',
 'babe goe day miss alreadi love love kiss hope everyth goe well',
 'urgent tri contact last weekend draw show prize guarante call claim code k valid hour',
 'hey mate spoke mag peopl deliv end month deliv th sept talk later',
 'happen dear tell',
 'exactli anyway far jide studi visit',
 'oh god found number glad text back xafter msg cst std ntwk chg',
 'fine give call know want question',
 'oh ok prob',
 'dont thnk wrong call us',
 'thread wishlist section forum ppl post nitro request start last page collect bottom',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'tuesday night r u real',
 'lara said loan lt gt',
 'alrit jod how revis goin keri bin doin smidgin n e way u wanna cum colleg xx',
 'dear voucher holder claim week offer pc pleas go http www wtlp co uk text ts cs appli',
 'geeeee internet realli bad today eh',
 'lol wtf random btw lunch break',
 'hi sexychat girl wait text text great night chat send stop stop servic',
 'sorri help',
 'whore unbeliev',
 'got take take part wrc ralli oz u lucozad energi text ralli le p see pack lucozad co uk wrc itcould u',
 'abl sleep',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'noe specifi da domain nusstu still sch',
 'daddi bb',
 'puriti friendship two smile read forward messag smile see name gud evng',
 'ju reach home go bath first si use net tell u finish k',
 'said anyth wrong sorri de',
 'stupid say challeng god dont think write instead respond im',
 'oki thanx',
 'import custom servic announc call freephon',
 'type stuff sing',
 'tessi pl favor pl convey birthday wish nimya pl dnt forget today birthday shija',
 'might accid tookplac somewher ghodbandar rd traffic move slove plz slip amp worri',
 'love night wake see messag hope smile know great morn',
 'hey angri repli dr',
 'bluray player',
 'dun believ leh tot told true alreadi thk muz c us tog believ',
 'opinion jada kusruthi lovabl silent spl charact matur stylish simpl pl repli',
 'hey want anyth buy',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'look',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'well avail washob nob last night ask nickey platt instead',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'tell happen dont behav like ok need say',
 'fuck chicken messag would late woould buzz hear word',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'yuou work get pc mom find spot would work need',
 'ju hope true missin co realli missin done anyth feel guilti yet',
 'howz person stori',
 'realli hope work doesnt get stress gr day',
 'call cost guess isnt bad miss ya need ya want ya love ya',
 'gud mrng dear hav nice day',
 'wait till end march el nino get oh',
 'ur chang da report big co alreadi made chang da previou report',
 'urgent mobil award bonu caller prize nd attempt contact call box qu',
 'one',
 'remain unconvinc elabor test willpow',
 'u got person stori',
 'train manual show tech process password reset troubleshoot',
 'wait tv show start lor u leh still busi ur report',
 'hey thk juz go accordin wat discuss yest lor except kb sun co nt much lesson go attend kb sat',
 'aight pick open tonight',
 'want leav bare stay sane fight constantli help',
 'haha hope hear receipt sound gd luck',
 'neft transact refer number lt gt rs lt decim gt credit beneficiari account lt gt lt time gt lt gt',
 'got lt gt way could pick',
 'nope forgot show next week',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg txtauction',
 'hey chief give bell get need talk royal visit st june',
 'weird know one point',
 'dude teresa hope okay didnt hear peopl call receiv packag sinc dec lt gt thot ld like know fantast year best read plu realli realli bam first aid usml work done',
 'ya nice readi thursday',
 'yup leav right back soon',
 'sir receiv account anoth hr time sorri delay',
 'urgent tri contact last weekend draw show u prize guarante call claim code k valid hr p pm',
 'sorri miss babe late slept hope enjoy drive lesson boytoy miss teas kiss',
 'thank rington order refer number x mobil charg tone arriv pleas call custom servic',
 'lol well without could big sale togeth',
 'hey go lo lesson gym',
 'hi hope u r ok said would text u seen let gentli pleas',
 'hank lotsli',
 'home',
 'tire slept well past night',
 'probabl around mu lot',
 'justbeen overa week sinc broke alreadi brain go mush',
 'thank u',
 'tessi pl favor pl convey birthday wish nimya pl dnt forget today birthday shija',
 'pleas tell special stock talk',
 'ic lotta childporn car',
 'want say holi shit guy kid bud',
 'hi im relax time ever get everi day parti good night get home tomorrow ish',
 'meet call later',
 'wat da model num ur phone',
 'cant pick phone right pl send messag',
 'burger king wanna play footi top stadium get burger king st sept go larg super coca cola walk winner',
 'velli good ye pleas',
 'u send home first ok lor readi yet',
 'sorri dude dont know forgot even dan remind sorri hope guy fun',
 'well done costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min',
 'hmm yeah groov im look forward pound special',
 'desir u go doctor liver get bit stylish get ur hair manag that',
 'ela kano il download come wen ur free',
 'realli good dhanush rock',
 'u noe send file comput',
 'send pic like',
 'k k go tirunelvali week see uncl alreadi spend amount take dress want money give feb',
 'got call landlin number ask come anna nagar go afternoon',
 'went pay rent go bank authoris payment',
 'network job',
 'home',
 'wonder phone batteri went dead tell love babe',
 'see shadow get earli spring yay',
 'alway braini one',
 'aight thank comin',
 'like',
 'sir wait call free pleas call',
 'aiya discuss later lar pick',
 'tri find chines food place around',
 'accordingli repeat text word ok mobil phone send',
 'r go send',
 'ou guarante latest nokia phone gb ipod mp player prize txt word collect ibhltd ldnw h p mtmsgrcvd',
 'simpl arithmet percentag',
 'make fuck sake x',
 'wors use half way stop better complet',
 'naughti littl thought better flirt flirt n flirt rather love someon n gettin hurt hurt n hurt gud nyt',
 'okay soon best',
 'die e toot fring',
 'laid airtel line rest',
 'tri figur suppos see coupl differ peopl week said get togeth set date',
 'urgent mobil award bonu caller prize nd attempt contact call box qu',
 'thank meet monday',
 'help u swoop pick u wherev ur bird r meet u want',
 'rct thnq adrian u text rgd vatian',
 'k must book huh go yoga basic sunday',
 'howz person stori',
 'convey regard',
 'mean fat head',
 'ok much though h friday cant wait dunno wot hell im gonna anoth week becom slob oh wait alreadi done',
 'send email mind lt gt time per night',
 'tkt euro cup final cash collect call b pobox ppm',
 'pleas ask macho price rang want someth new use plu interfu blackberri bold lt gt bb',
 'ask u meet da ge tmr nite',
 'meet u work tel shall work tomorrow',
 'ok april cant wait',
 'movi laptop',
 'dear take care reach home love u lot',
 'like new mobil',
 'award sipix digit camera call landlin deliveri within day cs box bp yr warranti ppm p p',
 'nokia get win free auction take part send nokia hg suit land row w jhl',
 'urgent mobil number award ukp prize guarante call landlin claim valid hr ppm',
 'norm tomorrow finish co st test need sort librari stuff point tomo got letter today access til end march better get move',
 'yo guess drop',
 'want come onlin',
 'hurt n meaning line ever compromis everyth love end love compromis everyth gud mornin',
 'gentl princess make sweet gentl love',
 'come slave go shell unconsci avoid make unhappi',
 'oh unintent bad time great finger train play along give fifteen min warn',
 'romcapspam everyon around respond well presenc sinc warm outgo bring real breath sunshin',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'pete pleas ring meiv hardli gotani credit',
 'will go aptitud class',
 'xma stori peac xma msg love xma miracl jesu hav bless month ahead amp wish u merri xma',
 'watch movi alreadi xy want shop shop w',
 'guy plan come',
 'haha yeah oz kind shitload',
 'decid peopl care stuff vote care stuff loser',
 'prize go anoth custom c www c biz p min polo ltd suit london w j hl pleas call back busi',
 'ok may free gym',
 'moment day valu morn bring hope afternoon bring faith even bring luv night bring rest wish u find today good morn',
 'number',
 'fujitsu seri lifebook good',
 'sm auction nokia get win free auction take part send nokia hg suit land row w jhl',
 'medic mission nigeria',
 'get chicken broth want ramen unless know',
 'nope c',
 'aww first time u said u miss without ask miss u first love',
 'chosen receiv award pl call claim number collect award select receiv valu mobil custom',
 'know lack particular dramastorm detail part worri',
 'ur chanc win cash everi wk txt action c www movietrivia tv custcar x p wk',
 'pl confirm time collect chequ',
 'still custom place',
 'motiv behind everi dark shine light wait find behind everi best friend alway trust love bslvyl',
 'thanx yup come back sun finish dinner go back hotel time fli tog exactli mth today hope haf mani mth come',
 'get brand new mobil phone agent mob plu load goodi info text mat',
 'hous maid murder coz man murder lt gt th januari public holiday govt instituit close includ post offic understand',
 'da today also forgot',
 'ok come n pick u engin',
 'next month get upto call ur standard network charg activ call c wire net st term pobox uz cost min mobcudb',
 'jay told alreadi',
 'unfortun found pick sister airport even think go tri go one th',
 'say hi drugdeal',
 'keep ten rs shelf buy two egg',
 'k roommat also want dubsack anoth friend may also want plan bring extra tell know sure',
 'think one say clearli ok leav need ask go come',
 'watch cartoon listen music amp eve go templ amp church u',
 'lol would despit cramp like girl',
 'got seventeen pound seven hundr ml hope ok',
 'uncl timi help clear car',
 'cool night lemm know around',
 'found enc lt gt',
 'hey cuti goe wale kinda ok like hill shit still avent kill',
 'carri disturb',
 'how watch resiz',
 'cant pick phone right pl send messag',
 'danc river',
 'want tell bad feel basic time text late need drug',
 'account xxxxxxxxx show unredeem point claim call identifi code xxxxx expir',
 'part initi understand',
 'haf msn yiju hotmail com',
 'wat late still earli mah juz go dinner lor aiya dunno',
 'sorri call later',

3. Apply BOW

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()

In [36]:
X_test=cv.transform(X_test).toarray()

In [37]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], shape=(4457, 2500))

In [38]:
cv.vocabulary_

{'hi': np.int64(934),
 'think': np.int64(2092),
 'match': np.int64(1256),
 'noth': np.int64(1452),
 'ok': np.int64(1475),
 'anyway': np.int64(76),
 'give': np.int64(804),
 'treat': np.int64(2169),
 'daddi': np.int64(482),
 'take': np.int64(2039),
 'good': np.int64(840),
 'care': np.int64(293),
 'get': np.int64(782),
 'ten': np.int64(2060),
 'call': np.int64(242),
 'text': np.int64(2069),
 'help': np.int64(927),
 'god': np.int64(830),
 'call text': np.int64(265),
 'guy': np.int64(891),
 'ask': np.int64(100),
 'say': np.int64(1785),
 'pleas': np.int64(1584),
 'messag': np.int64(1289),
 'wait': np.int64(2313),
 'wait call': np.int64(2314),
 'dear': np.int64(501),
 'invit': np.int64(1037),
 'final': np.int64(695),
 'attempt': np.int64(108),
 'contact': np.int64(409),
 'txt': np.int64(2193),
 'chat': np.int64(325),
 'suit': np.int64(2008),
 'land': np.int64(1101),
 'row': np.int64(1758),
 'hl': np.int64(944),
 'ldn': np.int64(1133),
 'yr': np.int64(2495),
 'attempt contact': np.int64(109),
 'txt chat': np.int64(2196),
 'suit land': np.int64(2009),
 'land row': np.int64(1103),
 'row hl': np.int64(1759),
 'hl ldn': np.int64(946),
 'white': np.int64(2388),
 'store': np.int64(1990),
 'thk': np.int64(2100),
 'got': np.int64(853),
 'wan': np.int64(2319),
 'come': np.int64(379),
 'wat': np.int64(2338),
 'wan come': np.int64(2320),
 'wish': np.int64(2407),
 'mani': np.int64(1248),
 'return': np.int64(1733),
 'day': np.int64(492),
 'happi': np.int64(908),
 'birthday': np.int64(174),
 'vikki': np.int64(2293),
 'mani mani': np.int64(1250),
 'return day': np.int64(1734),
 'day happi': np.int64(495),
 'happi birthday': np.int64(909),
 'move': np.int64(1366),
 'lot': np.int64(1204),
 'last': np.int64(1111),
 'difficult': np.int64(532),
 'know': np.int64(1094),
 'lt': np.int64(1220),
 'gt': np.int64(873),
 'around': np.int64(94),
 'lt gt': np.int64(1222),
 'bed': np.int64(154),
 'well': np.int64(2375),
 'need': np.int64(1405),
 'go': np.int64(812),
 'late': np.int64(1116),
 'school': np.int64(1793),
 'night': np.int64(1429),
 'especi': np.int64(630),
 'one': np.int64(1492),
 'class': np.int64(346),
 'miss': np.int64(1316),
 'wednesday': np.int64(2360),
 'probabl': np.int64(1642),
 'fail': np.int64(666),
 'test': np.int64(2068),
 'friday': np.int64(751),
 'think need': np.int64(2097),
 'sore': np.int64(1930),
 'throat': np.int64(2105),
 'talk': np.int64(2043),
 'free': np.int64(731),
 'pa': np.int64(1522),
 'free call': np.int64(733),
 'havent': np.int64(916),
 'plan': np.int64(1579),
 'buy': np.int64(233),
 'later': np.int64(1117),
 'check': np.int64(328),
 'alreadi': np.int64(49),
 'show': np.int64(1857),
 'afternoon': np.int64(29),
 'finish': np.int64(703),
 'work': np.int64(2429),
 'ah': np.int64(33),
 'thing': np.int64(2091),
 'receipt': np.int64(1690),
 'done': np.int64(556),
 'ye': np.int64(2475),
 'tell': np.int64(2058),
 'number': np.int64(1457),
 'could': np.int64(431),
 'ring': np.int64(1742),
 'well done': np.int64(2376),
 'freemsg': np.int64(746),
 'claim': np.int64(340),
 'ur': np.int64(2235),
 'sm': np.int64(1898),
 'use': np.int64(2269),
 'mobil': np.int64(1330),
 'mate': np.int64(1258),
 'etc': np.int64(632),
 'join': np.int64(1064),
 'com': np.int64(376),
 'wk': np.int64(2415),
 'box': np.int64(207),
 'la': np.int64(1097),
 'remov': np.int64(1712),
 'stop': np.int64(1980),
 'claim ur': np.int64(344),
 'ur sm': np.int64(2252),
 'ur mate': np.int64(2247),
 'teach': np.int64(2053),
 'app': np.int64(79),
 'da': np.int64(478),
 'colleg': np.int64(371),
 'even': np.int64(636),
 'friend': np.int64(752),
 'haha': np.int64(897),
 'mayb': np.int64(1269),
 'rite': np.int64(1747),
 'feel': np.int64(683),
 'like': np.int64(1160),
 'someon': np.int64(1915),
 'gd': np.int64(778),
 'lor': np.int64(1199),
 'faster': np.int64(676),
 'find': np.int64(696),
 'gal': np.int64(769),
 'group': np.int64(871),
 'liao': np.int64(1153),
 'feel like': np.int64(686),
 'love': np.int64(1206),
 'bu': np.int64(225),
 'dont': np.int64(557),
 'oh': np.int64(1473),
 'hope': np.int64(965),
 'month': np.int64(1351),
 'dont know': np.int64(558),
 'thinkin': np.int64(2099),
 'question': np.int64(1654),
 'gym': np.int64(893),
 'machan': np.int64(1231),
 'goodnight': np.int64(851),
 'bore': np.int64(200),
 'date': np.int64(490),
 'bt': np.int64(223),
 'nation': np.int64(1394),
 'rate': np.int64(1668),
 'min': np.int64(1299),
 'landlin': np.int64(1104),
 'bt nation': np.int64(224),
 'nation rate': np.int64(1395),
 'rate min': np.int64(1672),
 'close': np.int64(352),
 'urgent': np.int64(2259),
 'import': np.int64(1016),
 'inform': np.int64(1028),
 'user': np.int64(2270),
 'today': np.int64(2130),
 'lucki': np.int64(1227),
 'log': np.int64(1184),
 'onto': np.int64(1498),
 'http': np.int64(987),
 'www': np.int64(2450),
 'urawinn': np.int64(2257),
 'fantast': np.int64(672),
 'surpris': np.int64(2028),
 'await': np.int64(117),
 'import inform': np.int64(1017),
 'user today': np.int64(2271),
 'today lucki': np.int64(2135),
 'lucki day': np.int64(1228),
 'day find': np.int64(494),
 'find log': np.int64(698),
 'log onto': np.int64(1185),
 'onto http': np.int64(1499),
 'http www': np.int64(988),
 'www urawinn': np.int64(2457),
 'urawinn com': np.int64(2258),
 'com fantast': np.int64(377),
 'fantast surpris': np.int64(673),
 'surpris await': np.int64(2029),
 'entri': np.int64(624),
 'gr': np.int64(860),
 'prize': np.int64(1637),
 'wkli': np.int64(2418),
 'comp': np.int64(389),
 'chanc': np.int64(316),
 'win': np.int64(2398),
 'latest': np.int64(1120),
 'nokia': np.int64(1435),
 'cash': np.int64(300),
 'everi': np.int64(638),
 'great': np.int64(865),
 'free entri': np.int64(736),
 'comp chanc': np.int64(390),
 'chanc win': np.int64(318),
 'cash everi': np.int64(303),
 'everi wk': np.int64(642),
 'wk txt': np.int64(2416),
 'man': np.int64(1246),
 'make': np.int64(1239),
 'pretti': np.int64(1629),
 'babi': np.int64(129),
 'togeth': np.int64(2141),
 'wont': np.int64(2426),
 'anyth': np.int64(72),
 'de': np.int64(498),
 'earlier': np.int64(587),
 'station': np.int64(1970),
 'den': np.int64(519),
 'meet': np.int64(1277),
 'sen': np.int64(1818),
 'told': np.int64(2142),
 'uncl': np.int64(2221),
 'cbe': np.int64(308),
 'leav': np.int64(1137),
 'wif': np.int64(2394),
 'lar': np.int64(1108),
 'meh': np.int64(1280),
 'heavi': np.int64(923),
 'dun': np.int64(578),
 'drive': np.int64(572),
 'sch': np.int64(1791),
 'go sch': np.int64(824),
 'run': np.int64(1765),
 'ttyl': np.int64(2186),
 'ass': np.int64(104),
 'back': np.int64(130),
 'south': np.int64(1938),
 'tampa': np.int64(2044),
 'prefer': np.int64(1624),
 'say hi': np.int64(1787),
 'south tampa': np.int64(1939),
 'amp': np.int64(56),
 'good night': np.int64(847),
 'take care': np.int64(2040),
 'decim': np.int64(505),
 'hour': np.int64(977),
 'time': np.int64(2114),
 'feb': np.int64(682),
 'april': np.int64(85),
 'season': np.int64(1801),
 'lt decim': np.int64(1221),
 'decim gt': np.int64(506),
 'morn': np.int64(1356),
 'princess': np.int64(1632),
 'good morn': np.int64(846),
 'morn princess': np.int64(1360),
 'heard': np.int64(919),
 'xx': np.int64(2464),
 'luv': np.int64(1230),
 'net': np.int64(1409),
 'award': np.int64(120),
 'bonu': np.int64(196),
 'caller': np.int64(269),
 'line': np.int64(1166),
 'valid': np.int64(2278),
 'hr': np.int64(985),
 'urgent mobil': np.int64(2262),
 'mobil number': np.int64(1336),
 'number award': np.int64(1458),
 'award bonu': np.int64(121),
 'bonu caller': np.int64(197),
 'caller prize': np.int64(271),
 'prize call': np.int64(1638),
 'call land': np.int64(252),
 'land line': np.int64(1102),
 'valid hr': np.int64(2279),
 'sad': np.int64(1767),
 'stori': np.int64(1992),
 'week': np.int64(2362),
 'wife': np.int64(2395),
 'nt': np.int64(1454),
 'parent': np.int64(1527),
 'forgot': np.int64(724),
 'kid': np.int64(1086),
 'went': np.int64(2380),
 'colleagu': np.int64(367),
 'last week': np.int64(1114),
 'wife nt': np.int64(2396),
 'work even': np.int64(2430),
 'abiola': np.int64(1),
 'wish great': np.int64(2408),
 'great day': np.int64(866),
 'lol': np.int64(1190),
 'would': np.int64(2439),
 'awesom': np.int64(126),
 'promis': np.int64(1646),
 'send': np.int64(1819),
 'pic': np.int64(1560),
 'pleas send': np.int64(1586),
 'want': np.int64(2326),
 'new': np.int64(1416),
 'video': np.int64(2285),
 'phone': np.int64(1554),
 'anytim': np.int64(74),
 'network': np.int64(1411),
 'five': np.int64(707),
 'pound': np.int64(1614),
 'per': np.int64(1542),
 'repli': np.int64(1717),
 'deliveri': np.int64(515),
 'tomorrow': np.int64(2144),
 'want new': np.int64(2332),
 'new video': np.int64(1420),
 'video phone': np.int64(2287),
 'phone anytim': np.int64(1555),
 'anytim network': np.int64(75),
 'network min': np.int64(1412),
 'min text': np.int64(1303),
 'per week': np.int64(1548),
 'call repli': np.int64(261),
 'deliveri tomorrow': np.int64(516),
 'money': np.int64(1349),
 'worri': np.int64(2434),
 'due': np.int64(577),
 'two': np.int64(2192),
 'ago': np.int64(32),
 'lemm': np.int64(1146),
 'readi': np.int64(1683),
 'lemm know': np.int64(1147),
 'hey': np.int64(930),
 'sexi': np.int64(1841),
 'bun': np.int64(230),
 'word': np.int64(2427),
 'ym': np.int64(2490),
 'sexi bun': np.int64(1842),
 'hello': np.int64(926),
 'job': np.int64(1060),
 'lazi': np.int64(1130),
 'toward': np.int64(2163),
 'boytoy': np.int64(214),
 'get back': np.int64(783),
 'possibl': np.int64(1611),
 'dint': np.int64(538),
 'tri': np.int64(2171),
 'pl': np.int64(1570),
 'pl dont': np.int64(1572),
 'mum': np.int64(1381),
 'watch': np.int64(2343),
 'wan go': np.int64(2321),
 'throw': np.int64(2106),
 'decid': np.int64(504),
 'fyi': np.int64(767),
 'quick': np.int64(1655),
 'shower': np.int64(1860),
 'like lt': np.int64(1163),
 'gt min': np.int64(878),
 'sorri': np.int64(1931),
 'stuff': np.int64(1998),
 'actual': np.int64(14),
 'guy want': np.int64(892),
 'ya': np.int64(2468),
 'love ya': np.int64(1214),
 'offer': np.int64(1467),
 'handset': np.int64(904),
 'unlimit': np.int64(2226),
 'camcord': np.int64(275),
 'tri contact': np.int64(2173),
 'contact repli': np.int64(414),
 'repli offer': np.int64(1721),
 'video handset': np.int64(2286),
 'handset anytim': np.int64(905),
 'min unlimit': np.int64(1305),
 'unlimit text': np.int64(2227),
 'camcord repli': np.int64(276),
 'repli call': np.int64(1718),
 'mail': np.int64(1237),
 'onlin': np.int64(1497),
 'problem': np.int64(1643),
 'spend': np.int64(1951),
 'qualiti': np.int64(1653),
 'year': np.int64(2481),
 'new year': np.int64(1421),
 'fuck': np.int64(760),
 'merri': np.int64(1287),
 'christma': np.int64(336),
 'merri christma': np.int64(1288),
 'gonna': np.int64(838),
 'die': np.int64(530),
 'stay': np.int64(1971),
 'wake': np.int64(2317),
 'crave': np.int64(441),
 'indian': np.int64(1024),
 'nice': np.int64(1426),
 'tho': np.int64(2102),
 'bit': np.int64(176),
 'drink': np.int64(571),
 'sometim': np.int64(1922),
 'soon': np.int64(1929),
 'mite': np.int64(1321),
 'hav': np.int64(915),
 'laugh': np.int64(1127),
 'pete': np.int64(1552),
 'right': np.int64(1740),
 'one day': np.int64(1493),
 'yep': np.int64(2483),
 'fine': np.int64(701),
 'ice': np.int64(1001),
 'age': np.int64(31),
 'go back': np.int64(813),
 'ha': np.int64(894),
 'ju': np.int64(1072),
 'ate': np.int64(106),
 'honey': np.int64(962),
 'ar': np.int64(86),
 'sweet': np.int64(2032),
 'babe': np.int64(127),
 'im': np.int64(1011),
 'home': np.int64(960),
 'wanna': np.int64(2325),
 'someth': np.int64(1919),
 'hi babe': np.int64(935),
 'darlin': np.int64(487),
 'kate': np.int64(1077),
 'doin': np.int64(554),
 'somethin': np.int64(1921),
 'tonight': np.int64(2152),
 'pub': np.int64(1647),
 'hi darlin': np.int64(937),
 'yan': np.int64(2470),
 'jiu': np.int64(1059),
 'sat': np.int64(1778),
 'bugi': np.int64(229),
 'frm': np.int64(757),
 'hop': np.int64(964),
 'sun': np.int64(2012),
 'cine': np.int64(337),
 'mrt': np.int64(1371),
 'hip': np.int64(940),
 'yan jiu': np.int64(2471),
 'hip hop': np.int64(941),
 'custom': np.int64(467),
 'servic': np.int64(1833),
 'repres': np.int64(1724),
 'pm': np.int64(1592),
 'guarante': np.int64(881),
 'pleas call': np.int64(1585),
 'call custom': np.int64(247),
 'custom servic': np.int64(471),
 'servic repres': np.int64(1836),
 'pm guarante': np.int64(1593),
 'guarante cash': np.int64(883),
 'cash prize': np.int64(304),
 'go home': np.int64(819),
 'deni': np.int64(520),
 'left': np.int64(1142),
 'look': np.int64(1195),
 'mom': np.int64(1345),
 'want know': np.int64(2330),
 'cal': np.int64(241),
 'sir': np.int64(1877),
 'come home': np.int64(382),
 'carlo': np.int64(297),
 'mu': np.int64(1379),
 'minut': np.int64(1309),
 'gt minut': np.int64(879),
 'mind': np.int64(1306),
 'reason': np.int64(1689),
 'laptop': np.int64(1107),
 'noe': np.int64(1434),
 'slow': np.int64(1895),
 'fast': np.int64(675),
 'trip': np.int64(2176),
 'india': np.int64(1023),
 'bring': np.int64(217),
 'light': np.int64(1158),
 'everyon': np.int64(644),
 'project': np.int64(1645),
 'see': np.int64(1808),
 'smile': np.int64(1903),
 'bye': np.int64(237),
 'lover': np.int64(1215),
 'bf': np.int64(167),
 'hmmm': np.int64(948),
 'kick': np.int64(1085),
 'logo': np.int64(1188),
 'name': np.int64(1392),
 'heart': np.int64(920),
 'eg': np.int64(597),
 'eve': np.int64(635),
 'yahoo': np.int64(2469),
 'pobox': np.int64(1597),
 'wq': np.int64(2444),
 'ad': np.int64(15),
 'pobox wq': np.int64(1600),
 'old': np.int64(1488),
 'peopl': np.int64(1540),
 'better': np.int64(166),
 'lie': np.int64(1155),
 'alway': np.int64(53),
 'play': np.int64(1580),
 'joke': np.int64(1066),
 'sorri call': np.int64(1932),
 'call later': np.int64(254),
 'winner': np.int64(2406),
 'special': np.int64(1946),
 'select': np.int64(1813),
 'receiv': np.int64(1691),
 'holiday': np.int64(956),
 'flight': np.int64(713),
 'inc': np.int64(1018),
 'speak': np.int64(1943),
 'live': np.int64(1175),
 'oper': np.int64(1502),
 'special select': np.int64(1949),
 'select receiv': np.int64(1814),
 'speak live': np.int64(1944),
 'live oper': np.int64(1176),
 'oper claim': np.int64(1503),
 'still': np.int64(1974),
 'littl': np.int64(1174),
 'experi': np.int64(656),
 'understand': np.int64(2222),
 'voic': np.int64(2302),
 'still need': np.int64(1975),
 'fill': np.int64(692),
 'spook': np.int64(1954),
 'mob': np.int64(1327),
 'collect': np.int64(368),
 'plu': np.int64(1589),
 'eeri': np.int64(595),
 'tone': np.int64(2146),
 'card': np.int64(292),
 'zed': np.int64(2499),
 'logo pic': np.int64(1189),
 'plu free': np.int64(1590),
 'tone txt': np.int64(2150),
 'quit': np.int64(1656),
 'least': np.int64(1136),
 'much': np.int64(1380),
 'notic': np.int64(1453),
 'nah': np.int64(1390),
 'taunton': np.int64(2047),
 'want come': np.int64(2327),
 'reali': np.int64(1685),
 'start': np.int64(1966),
 'tv': np.int64(2190),
 'watch tv': np.int64(2345),
 'tv lor': np.int64(2191),
 'tm': np.int64(2124),
 'charg': np.int64(321),
 'shortli': np.int64(1856),
 'last night': np.int64(1112),
 'sent': np.int64(1829),
 'ive': np.int64(1048),
 'didnt': np.int64(528),
 'piss': np.int64(1567),
 'xxx': np.int64(2465),
 'hi babi': np.int64(936),
 'give call': np.int64(805),
 'aunti': np.int64(113),
 'nobodi': np.int64(1433),
 'suppos': np.int64(2023),
 'harri': np.int64(913),
 'order': np.int64(1513),
 'book': np.int64(199),
 'answer': np.int64(68),
 'first': np.int64(705),
 'woke': np.int64(2422),
 'fall': np.int64(667),
 'asleep': np.int64(103),
 'til': np.int64(2112),
 'easi': np.int64(589),
 'pay': np.int64(1535),
 'pay back': np.int64(1536),
 'interest': np.int64(1033),
 'tri make': np.int64(2175),
 'wrong': np.int64(2447),
 'doubl': np.int64(562),
 'best': np.int64(163),
 'orang': np.int64(1510),
 'tariff': np.int64(2045),
 'camera': np.int64(279),
 'mobileupd': np.int64(1340),
 'stoptxt': np.int64(1989),
 'cs': np.int64(452),
 'doubl min': np.int64(563),
 'orang tariff': np.int64(1511),
 'latest camera': np.int64(1121),
 'camera phone': np.int64(282),
 'phone free': np.int64(1557),
 'call mobileupd': np.int64(257),
 'luck': np.int64(1226),
 'catch': np.int64(306),
 'put': np.int64(1651),
 'complimentari': np.int64(394),
 'tenerif': np.int64(2064),
 'sae': np.int64(1768),
 'cw': np.int64(476),
 'wx': np.int64(2458),
 'ppm': np.int64(1618),
 'urgent pleas': np.int64(2263),
 'call landlin': np.int64(253),
 'tenerif holiday': np.int64(2065),
 'holiday cash': np.int64(958),
 'cash await': np.int64(301),
 'await collect': np.int64(118),
 'collect sae': np.int64(370),
 'sae cs': np.int64(1769),
 'cs box': np.int64(454),
 'box cw': np.int64(209),
 'cw wx': np.int64(477),
 'wx ppm': np.int64(2459),
 'regist': np.int64(1703),
 'subscrib': np.int64(2003),
 'draw': np.int64(565),
 'gift': np.int64(798),
 'voucher': np.int64(2305),
 'enter': np.int64(621),
 'correct': np.int64(425),
 'an': np.int64(61),
 'what': np.int64(2382),
 'draw gift': np.int64(566),
 'gift voucher': np.int64(800),
 'troubl': np.int64(2177),
 'expect': np.int64(654),
 'mine': np.int64(1308),
 'tomo': np.int64(2143),
 'place': np.int64(1578),
 'mnth': np.int64(1324),
 'half': np.int64(900),
 'top': np.int64(2155),
 'also': np.int64(52),
 'dun wan': np.int64(581),
 'ip': np.int64(1039),
 'address': np.int64(17),
 'consid': np.int64(408),
 'comput': np.int64(395),
 'nope': np.int64(1447),
 'meanwhil': np.int64(1273),
 'greet': np.int64(869),
 'infern': np.int64(1025),
 'affair': np.int64(25),
 'darren': np.int64(488),
 'xy': np.int64(2467),
 'wan watch': np.int64(2323),
 'watch infern': np.int64(2344),
 'infern affair': np.int64(1026),
 'us': np.int64(2268),
 'connect': np.int64(407),
 'bill': np.int64(171),
 'give us': np.int64(806),
 'said': np.int64(1772),
 'kiss': np.int64(1091),
 'sound': np.int64(1935),
 'effect': np.int64(596),
 'kind': np.int64(1088),
 'person': np.int64(1549),
 'voda': np.int64(2299),
 'end': np.int64(609),
 'quot': np.int64(1659),
 'code': np.int64(361),
 'standard': np.int64(1963),
 'today voda': np.int64(2140),
 'voda number': np.int64(2300),
 'number end': np.int64(1459),
 'end select': np.int64(611),
 'receiv award': np.int64(1692),
 'match pleas': np.int64(1257),
 'call quot': np.int64(260),
 'quot claim': np.int64(1660),
 'claim code': np.int64(342),
 'code standard': np.int64(363),
 'standard rate': np.int64(1964),
 'rate app': np.int64(1669),
 'privat': np.int64(1635),
 'account': np.int64(8),
 'statement': np.int64(1968),
 'un': np.int64(2218),
 'redeem': np.int64(1697),
 'point': np.int64(1601),
 'identifi': np.int64(1004),
 'expir': np.int64(657),
 'privat account': np.int64(1636),
 'account statement': np.int64(9),
 'statement show': np.int64(1969),
 'show un': np.int64(1859),
 'un redeem': np.int64(2219),
 'redeem point': np.int64(1698),
 'point call': np.int64(1602),
 'call identifi': np.int64(250),
 'identifi code': np.int64(1005),
 'code expir': np.int64(362),
 'congrat': np.int64(403),
 'id': np.int64(1002),
 'otherwis': np.int64(1520),
 'world': np.int64(2432),
 'fun': np.int64(764),
 'fact': np.int64(665),
 'armand': np.int64(93),
 'shit': np.int64(1852),
 'smoke': np.int64(1906),
 'hit': np.int64(942),
 'way': np.int64(2348),
 'ticket': np.int64(2111),
 'comin': np.int64(387),
 'compani': np.int64(391),
 'pl send': np.int64(1577),
 'ga': np.int64(768),
 'natur': np.int64(1396),
 'want go': np.int64(2329),
 'drug': np.int64(575),
 'yet': np.int64(2488),
 'never': np.int64(1415),
 'origin': np.int64(1515),
 'either': np.int64(600),
 'msg': np.int64(1373),
 'iam': np.int64(998),
 'bcoz': np.int64(147),
 'bslvyl': np.int64(222),
 'rington': np.int64(1743),
 'club': np.int64(354),
 'uk': np.int64(2213),
 'singl': np.int64(1874),
 'choos': np.int64(335),
 'yup': np.int64(2497),
 'thanx': np.int64(2086),
 'print': np.int64(1634),
 'hand': np.int64(903),
 'arrang': np.int64(96),
 'thank': np.int64(2082),
 'bad': np.int64(133),
 'futur': np.int64(766),
 'drop': np.int64(574),
 'text free': np.int64(2073),
 'thursday': np.int64(2109),
 'whole': np.int64(2389),
 'hous': np.int64(978),
 'scream': np.int64(1796),
 'pull': np.int64(1648),
 'hair': np.int64(899),
 'small': np.int64(1902),
 'tablet': np.int64(2038),

4. Training the model

In [39]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [40]:
y_pred=spam_detect_model.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score,classification_report

5. evaluating the model

In [42]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9847533632286996

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.92      0.94       152
           1       0.99      0.99      0.99       963

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [46]:
X_train=tfidf.fit_transform(X_train).toarray()
X_test=tfidf.transform(X_test).toarray()

In [47]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [48]:
y_pred=spam_detect_model.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score,classification_report

In [50]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.97847533632287

In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.86      0.91       150
           1       0.98      1.00      0.99       965

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115

In [52]:
!pip install gensim

Requirement already satisfied: gensim in c:\users\dheer\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\dheer\anaconda3\lib\site-packages (from gensim) (2.4.2)
Requirement already satisfied: scipy>=1.7.0 in c:\users\dheer\anaconda3\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\dheer\anaconda3\lib\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in c:\users\dheer\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [53]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [54]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [55]:
len(corpus)

5572

In [56]:
messages.shape

(5572, 2)

In [57]:
words=[]
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [58]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'appli'],
 ['dun', 'say', 'earli', 'hor', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select',
  'receivea',
  'prize',
  'reward',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour'],
 ['mobil',
  'month',
  'entitl',
  'updat',
  'latest',
  'colour',
  'mobil',
  'camera',
  'free',
  'call',
  'mobil',
  'updat',
  'co',
  'free'],
 ['gonna',
  'home',
  'soon',
  'want',
  'talk',
  'stuff',
  'anymor',
  'tonight',
  'cri',
  'enough',
  'today'],
 ['six',
  'chanc',
  'win',
  'cash',
  'pound',
  'txt',
  'csh',
  'send',
  'cost',
  'day',
  'day',
  'tsandc',
  'appli',
  'repli',
  'hl',
  'info'],
 ['urgent',
  'week',
  'free',
  'membership',
  'prize',
  'jackpot',
  'txt',
  'word',
  'claim',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['search',
  'right',
  'word',
  'thank',
  'breather',
  'promis',
  'wont',
  'take',
  'help',
  'grant',
  'fulfil',
  'promis',
  'wonder',
  'bless',
  'time'],
 ['date', 'sunday'],
 ['use',
  'credit',
  'click',
  'wap',
  'link',
  'next',
  'txt',
  'messag',
  'click',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watch'],
 ['eh', 'rememb', 'spell', 'name', 'ye', 'naughti', 'make', 'wet'],
 ['fine', 'way', 'feel', 'way', 'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'nation',
  'team',
  'eg',
  'england',
  'tri',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['serious', 'spell', 'name'],
 ['go', 'tri', 'month', 'ha', 'ha', 'joke'],
 ['pay', 'first', 'lar', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'lunch',
  'go',
  'str',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'alreadi'],
 ['ffffffffff', 'alright', 'way', 'meet', 'sooner'],
 ['forc',
  'eat',
  'slice',
  'realli',
  'hungri',
  'tho',
  'suck',
  'mark',
  'get',
  'worri',
  'know',
  'sick',
  'turn',
  'pizza',
  'lol'],
 ['lol', 'alway', 'convinc'],
 ['catch',
  'bu',
  'fri',
  'egg',
  'make',
  'tea',
  'eat',
  'mom',
  'left',
  'dinner',
  'feel',
  'love'],
 ['back', 'amp', 'pack', 'car', 'let', 'know', 'room'],
 ['ahhh', 'work', 'vagu', 'rememb', 'feel', 'like', 'lol'],
 ['wait', 'still', 'clear', 'sure', 'sarcast', 'want', 'live', 'us'],
 ['yeah',
  'got',
  'apologet',
  'fallen',
  'actin',
  'like',
  'spoilt',
  'child',
  'got',
  'caught',
  'till',
  'go',
  'badli',
  'cheer'],
 ['tell', 'anyth'],
 ['fear', 'faint', 'housework', 'quick', 'cuppa'],
 ['thank',
  'subscript',
  'rington',
  'uk',
  'mobil',
  'charg',
  'month',
  'pleas',
  'confirm',
  'repli',
  'ye',
  'repli',
  'charg'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'time',
  'msg',
  'xuhui',
  'go',
  'learn',
  'nd',
  'may',
  'lesson'],
 ['oop', 'let', 'know', 'roommat', 'done'],
 ['see', 'letter', 'car'],
 ['anyth', 'lor', 'decid'],
 ['hello',
  'saturday',
  'go',
  'text',
  'see',
  'decid',
  'anyth',
  'tomo',
  'tri',
  'invit',
  'anyth'],
 ['pl', 'go', 'ahead', 'watt', 'want', 'sure', 'great', 'weekend', 'abiola'],
 ['forget',
  'tell',
  'want',
  'need',
  'crave',
  'love',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummi'],
 ['rodger',
  'burn',
  'msg',
  'tri',
  'call',
  'repli',
  'sm',
  'free',
  'nokia',
  'mobil',
  'free',
  'camcord',
  'pleas',
  'call',
  'deliveri',
  'tomorrow'],
 ['see'],
 ['great', 'hope', 'like', 'man', 'well', 'endow', 'lt', 'gt', 'inch'],
 ['call', 'messag', 'miss', 'call'],
 ['get', 'hep', 'immunis', 'nigeria'],
 ['fair', 'enough', 'anyth', 'go'],
 ['yeah', 'hope', 'tyler', 'could', 'mayb', 'ask', 'around', 'bit'],
 ['know',
  'stubborn',
  'even',
  'want',
  'go',
  'hospit',
  'kept',
  'tell',
  'mark',
  'weak',
  'sucker',
  'hospit',
  'weak',
  'sucker'],
 ['think', 'first', 'time', 'saw', 'class'],
 ['gram',
  'usual',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'smarter',
  'though',
  'get',
  'almost',
  'whole',
  'second',
  'gram',
  'lt',
  'gt'],
 ['fyi', 'ride', 'earli', 'tomorrow', 'morn', 'crash', 'place', 'tonight'],
 ['wow',
  'never',
  'realiz',
  'embarass',
  'accomod',
  'thought',
  'like',
  'sinc',
  'best',
  'could',
  'alway',
  'seem',
  'happi',
  'cave',
  'sorri',
  'give',
  'sorri',
  'offer',
  'sorri',
  'room',
  'embarass'],
 ['sm',
  'ac',
  'sptv',
  'new',
  'jersey',
  'devil',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'incorrect',
  'end',
  'repli',
  'end',
  'sptv'],
 ['know', 'mallika', 'sherawat', 'yesterday', 'find', 'lt', 'url', 'gt'],
 ['congrat',
  'year',
  'special',
  'cinema',
  'pass',
  'call',
  'suprman',
  'matrix',
  'starwar',
  'etc',
  'free',
  'bx',
  'ip',
  'pm',
  'dont',
  'miss'],
 ['sorri', 'call', 'later', 'meet'],
 ['tell', 'reach'],
 ['ye', 'gauti', 'sehwag', 'odi', 'seri'],
 ['gonna', 'pick', 'burger', 'way', 'home', 'even', 'move', 'pain', 'kill'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'situat', 'seeker'],
 ['part', 'check', 'iq'],
 ['sorri', 'roommat', 'took', 'forev', 'ok', 'come'],
 ['ok',
  'lar',
  'doubl',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'alreadi',
  'said',
  'wun',
  'cut',
  'short',
  'said',
  'cut',
  'look',
  'nice'],
 ['valu',
  'custom',
  'pleas',
  'advis',
  'follow',
  'recent',
  'review',
  'mob',
  'award',
  'bonu',
  'prize',
  'call'],
 ['today',
  'song',
  'dedic',
  'day',
  'song',
  'dedic',
  'send',
  'ur',
  'valuabl',
  'frnd',
  'first',
  'rpli'],
 ['urgent',
  'ur',
  'award',
  'complimentari',
  'trip',
  'eurodisinc',
  'trav',
  'aco',
  'entri',
  'claim',
  'txt',
  'di',
  'morefrmmob',
  'ls',
  'aj'],
 ['hear', 'new', 'divorc', 'barbi', 'come', 'ken', 'stuff'],
 ['plane', 'give', 'month', 'end'],
 ['wah', 'lucki', 'man', 'save', 'money', 'hee'],
 ['finish', 'class'],
 ['hi', 'babe', 'im', 'home', 'wanna', 'someth', 'xx'],
 ['perform'],
 ['call'],
 ['wait', 'machan', 'call', 'free'],
 ['that', 'cool', 'gentleman', 'treat', 'digniti', 'respect'],
 ['like', 'peopl', 'much', 'shi', 'pa'],
 ['oper', 'lt', 'gt'],
 ['still', 'look', 'job', 'much', 'ta', 'earn'],
 ['sorri', 'call', 'later'],
 ['call', 'ah'],
 ['ok', 'way', 'home', 'hi', 'hi'],
 ['place', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'later', 'network', 'urgnt', 'sm'],
 ['real',
  'get',
  'yo',
  'need',
  'ticket',
  'one',
  'jacket',
  'done',
  'alreadi',
  'use',
  'multi'],
 ['ye',
  'start',
  'send',
  'request',
  'make',
  'pain',
  'came',
  'back',
  'back',
  'bed',
  'doubl',
  'coin',
  'factori',
  'gotta',
  'cash',
  'nitro'],
 ['realli', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah', 'stand', 'close', 'tho', 'catch', 'someth'],
 ['sorri',
  'pain',
  'ok',
  'meet',
  'anoth',
  'night',
  'spent',
  'late',
  'afternoon',
  'casualti',
  'mean',
  'done',
  'stuff',
  'moro',
  'includ',
  'time',
  'sheet',
  'sorri'],
 ['smile',
  'pleasur',
  'smile',
  'pain',
  'smile',
  'troubl',
  'pour',
  'like',
  'rain',
  'smile',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someon',
  'still',
  'love',
  'see',
  'smile'],
 ['pleas',
  'call',
  'custom',
  'servic',
  'repres',
  'pm',
  'guarante',
  'cash',
  'prize'],
 ['havent',
  'plan',
  'buy',
  'later',
  'check',
  'alreadi',
  'lido',
  'got',
  'show',
  'afternoon',
  'finish',
  'work',
  'alreadi'],
 ['free',
  'rington',
  'wait',
  'collect',
  'simpli',
  'text',
  'password',
  'mix',
  'verifi',
  'get',
  'usher',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watch', 'telugu', 'movi', 'wat', 'abt'],
 ['see', 'finish', 'load', 'loan', 'pay'],
 ['hi',
  'wk',
  'ok',
  'hol',
  'ye',
  'bit',
  'run',
  'forgot',
  'hairdress',
  'appoint',
  'four',
  'need',
  'get',
  'home',
  'shower',
  'beforehand',
  'caus',
  'prob'],
 ['see', 'cup', 'coffe', 'anim'],
 ['pleas', 'text', 'anymor', 'noth', 'els', 'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'legal',
  'wen',
  'pick',
  'ave',
  'am',
  'xx'],
 ['still', 'look', 'car', 'buy', 'gone', 'drive', 'test', 'yet'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['wow',
  'right',
  'mean',
  'guess',
  'gave',
  'boston',
  'men',
  'chang',
  'search',
  'locat',
  'nyc',
  'someth',
  'chang',
  'cuz',
  'signin',
  'page',
  'still',
  'say',
  'boston'],
 ['umma', 'life', 'vava', 'umma', 'love', 'lot', 'dear'],
 ['thank',
  'lot',
  'wish',
  'birthday',
  'thank',
  'make',
  'birthday',
  'truli',
  'memor'],
 ['aight', 'hit', 'get', 'cash'],
 ['would', 'ip', 'address', 'test', 'consid', 'comput', 'minecraft', 'server'],
 ['know',
  'grumpi',
  'old',
  'peopl',
  'mom',
  'like',
  'better',
  'lie',
  'alway',
  'one',
  'play',
  'joke'],
 ['dont', 'worri', 'guess', 'busi'],
 ['plural', 'noun', 'research'],
 ['go', 'dinner', 'msg'],
 ['ok',
  'wif',
  'co',
  'like',
  'tri',
  'new',
  'thing',
  'scare',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'loud'],
 ['gent',
  'tri',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guarante',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentenc',
  'formal',
  'anyway',
  'fine',
  'juz',
  'tt',
  'eatin',
  'much',
  'puttin',
  'weight',
  'haha',
  'anythin',
  'special',
  'happen'],
 ['enter',
  'cabin',
  'pa',
  'said',
  'happi',
  'day',
  'boss',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invit',
  'apart',
  'went'],
 ['winner',
  'special',
  'select',
  'receiv',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'oper',
  'claim',
  'min'],
 ['goodo',
  'ye',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'tortilla',
  'need'],
 ['hmm', 'uncl', 'inform', 'pay', 'school', 'directli', 'pl', 'buy', 'food'],
 ['privat',
  'account',
  'statement',
  'show',
  'unredeem',
  'bonu',
  'point',
  'claim',
  'call',
  'identifi',
  'code',
  'expir'],
 ['urgent',
  'mobil',
  'award',
  'bonu',
  'caller',
  'prize',
  'final',
  'tri',
  'contact',
  'call',
  'landlin',
  'box',
  'wr',
  'ppm'],
 ['new', 'address', 'appl', 'pair', 'malarki'],
 ['today',
  'voda',
  'number',
  'end',
  'select',
  'receiv',
  'award',
  'match',
  'pleas',
  'call',
  'quot',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['go', 'sao', 'mu', 'today', 'done'],
 ['predict', 'wat', 'time', 'finish', 'buy'],
 ['good', 'stuff'],
 ['know',
  'yetund',
  'sent',
  'money',
  'yet',
  'sent',
  'text',
  'bother',
  'send',
  'dont',
  'involv',
  'anyth',
  'impos',
  'anyth',
  'first',
  'place',
  'apologis'],
 ['room'],
 ['hey',
  'girl',
  'hope',
  'well',
  'del',
  'bak',
  'long',
  'time',
  'give',
  'call',
  'sum',
  'time',
  'lucyxx'],
 ['much', 'cost'],
 ['home'],
 ['dear', 'call', 'tmorrow', 'pl', 'accomod'],
 ['first', 'answer', 'question'],
 ['sunshin',
  'quiz',
  'wkli',
  'win',
  'top',
  'soni',
  'dvd',
  'player',
  'know',
  'countri',
  'algarv',
  'txt',
  'ansr',
  'sp',
  'tyron'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dog',
  'locat',
  'sent',
  'direct',
  'ur',
  'mob',
  'join',
  'uk',
  'largest',
  'dog',
  'network',
  'bt',
  'txting',
  'gravel',
  'nt',
  'ec',
  'msg'],
 ['haf', 'msn', 'yiju', 'hotmail', 'com'],
 ['call', 'meet'],
 ['check', 'room', 'befor', 'activ'],
 ['rcv',
  'msg',
  'chat',
  'svc',
  'free',
  'hardcor',
  'servic',
  'text',
  'go',
  'get',
  'noth',
  'must',
  'age',
  'verifi',
  'yr',
  'network',
  'tri'],
 ['got', 'lazi', 'type', 'forgot', 'lect', 'saw', 'pouch', 'like', 'nice'],
 ['text', 'way'],
 ['sir', 'wait', 'mail'],
 ['swt',
  'thought',
  'nver',
  'get',
  'tire',
  'littl',
  'thing',
  'lovabl',
  'person',
  'coz',
  'somtim',
  'littl',
  'thing',
  'occupi',
  'biggest',
  'part',
  'heart',
  'gud',
  'ni'],
 ['know', 'pl', 'open', 'back'],
 ['ye', 'see', 'ya', 'dot'],
 ['what', 'staff', 'name', 'take', 'class', 'us'],
 ['freemsg',
  'repli',
  'text',
  'randi',
  'sexi',
  'femal',
  'live',
  'local',
  'luv',
  'hear',
  'netcollex',
  'ltd',
  'per',
  'msg',
  'repli',
  'stop',
  'end'],
 ['ummma', 'call', 'check', 'life', 'begin', 'qatar', 'pl', 'pray', 'hard'],
 ['delet', 'contact'],
 ['sindu', 'got', 'job', 'birla', 'soft'],
 ['wine', 'flow', 'never'],
 ['yup', 'thk', 'cine', 'better', 'co', 'need', 'go', 'plaza', 'mah'],
 ['ok', 'ur', 'typic', 'repli'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['everywher',
  'dirt',
  'floor',
  'window',
  'even',
  'shirt',
  'sometim',
  'open',
  'mouth',
  'come',
  'flow',
  'dream',
  'world',
  'without',
  'half',
  'chore',
  'time',
  'joy',
  'lot',
  'tv',
  'show',
  'see',
  'guess',
  'like',
  'thing',
  'must',
  'exist',
  'like',
  'rain',
  'hail',
  'mist',
  'time',
  'done',
  'becom',
  'one'],
 ['aaooooright', 'work'],
 ['leav', 'hous'],
 ['hello',
  'love',
  'get',
  'interview',
  'today',
  'happi',
  'good',
  'boy',
  'think',
  'miss'],
 ['custom',
  'servic',
  'annonc',
  'new',
  'year',
  'deliveri',
  'wait',
  'pleas',
  'call',
  'arrang',
  'deliveri'],
 ['winner',
  'special',
  'select',
  'receiv',
  'cash',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'oper',
  'claim'],
 ['keep',
  'safe',
  'need',
  'miss',
  'alreadi',
  'envi',
  'everyon',
  'see',
  'real',
  'life'],
 ['new', 'car', 'hous', 'parent', 'new', 'job', 'hand'],
 ['love', 'excit', 'day', 'spend', 'make', 'happi'],
 ['pl',
  'stop',
  'bootydeli',
  'invit',
  'friend',
  'repli',
  'ye',
  'see',
  'www',
  'sm',
  'ac',
  'bootydeli',
  'stop',
  'send',
  'stop',
  'frnd'],
 ['bangbab',
  'ur',
  'order',
  'way',
  'receiv',
  'servic',
  'msg',
  'download',
  'ur',
  'content',
  'goto',
  'wap',
  'bangb',
  'tv',
  'ur',
  'mobil',
  'internet',
  'servic',
  'menu'],
 ['place', 'ur', 'point', 'cultur', 'modul', 'alreadi'],
 ['urgent',
  'tri',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guarante',
  'call',
  'claim',
  'code',
  'valid',
  'hr'],
 ['hi', 'frnd', 'best', 'way', 'avoid', 'missunderstd', 'wit', 'belov', 'one'],
 ['great', 'escap', 'fanci', 'bridg', 'need', 'lager', 'see', 'tomo'],
 ['ye', 'complet', 'form', 'clark', 'also', 'utter', 'wast'],
 ['sir', 'need', 'axi', 'bank', 'account', 'bank', 'address'],
 ['hmmm',
  'thk',
  'sure',
  'got',
  'time',
  'hop',
  'ard',
  'ya',
  'go',
  'free',
  'abt',
  'muz',
  'call',
  'discuss',
  'liao'],
 ['time', 'come', 'later'],
 ['bloodi',
  'hell',
  'cant',
  'believ',
  'forgot',
  'surnam',
  'mr',
  'ill',
  'give',
  'clue',
  'spanish',
  'begin'],
 ['well', 'gonna', 'finish', 'bath', 'good', 'fine', 'night'],
 ['let', 'know', 'got', 'money', 'carlo', 'make', 'call'],
 ['still', 'go', 'mall'],
 ['turn',
  'friend',
  'stay',
  'whole',
  'show',
  'back',
  'til',
  'lt',
  'gt',
  'feel',
  'free',
  'go',
  'ahead',
  'smoke',
  'lt',
  'gt',
  'worth'],
 ['text', 'doesnt', 'repli', 'let', 'know', 'log'],
 ['hi',
  'spoke',
  'maneesha',
  'like',
  'know',
  'satisfi',
  'experi',
  'repli',
  'toll',
  'free',
  'ye'],
 ['lift',
  'hope',
  'offer',
  'money',
  'need',
  'especi',
  'end',
  'month',
  'approach',
  'hurt',
  'studi',
  'anyway',
  'gr',
  'weekend'],
 ['lol', 'trust'],
 ['ok', 'gentleman', 'treat', 'digniti', 'respect'],
 ['guy', 'close'],
 ['go', 'noth', 'great', 'bye'],
 ['hello',
  'handsom',
  'find',
  'job',
  'lazi',
  'work',
  'toward',
  'get',
  'back',
  'net',
  'mummi',
  'boytoy',
  'miss'],
 ['haha', 'awesom', 'minut'],
 ['pleas',
  'call',
  'custom',
  'servic',
  'repres',
  'freephon',
  'pm',
  'guarante',
  'cash',
  'prize'],
 ['got', 'xma', 'radio', 'time', 'get'],
 ['ju',
  'reach',
  'home',
  'go',
  'bath',
  'first',
  'si',
  'use',
  'net',
  'tell',
  'finish'],
 ['uniqu', 'enough', 'find', 'th', 'august', 'www', 'areyouuniqu', 'co', 'uk'],
 ['sorri',
  'join',
  'leagu',
  'peopl',
  'dont',
  'keep',
  'touch',
  'mean',
  'great',
  'deal',
  'friend',
  'time',
  'even',
  'great',
  'person',
  'cost',
  'great',
  'week'],
 ['hi', 'final', 'complet', 'cours'],
 ['stop',
  'howev',
  'suggest',
  'stay',
  'someon',
  'abl',
  'give',
  'or',
  'everi',
  'stool'],
 ['hope', 'settl', 'new', 'school', 'year', 'wishin', 'gr', 'day'],
 ['gud', 'mrng', 'dear', 'hav', 'nice', 'day'],
 ['got', 'person', 'stori'],
 ['hamster', 'dead', 'hey', 'tmr', 'meet', 'pm', 'orchard', 'mrt'],
 ['hi',
  'kate',
  'even',
  'hope',
  'see',
  'tomorrow',
  'bit',
  'bloodi',
  'babyjontet',
  'txt',
  'back',
  'xxx'],
 ['found', 'enc', 'lt', 'gt'],
 ['sent', 'lt', 'gt', 'buck'],
 ['hello',
  'darlin',
  'ive',
  'finish',
  'colleg',
  'txt',
  'finish',
  'love',
  'kate',
  'xxx'],
 ['account',
  'refil',
  'success',
  'inr',
  'lt',
  'decim',
  'gt',
  'keralacircl',
  'prepaid',
  'account',
  'balanc',
  'rs',
  'lt',
  'decim',
  'gt',
  'transact',
  'id',
  'kr',
  'lt',
  'gt'],
 ['goodmorn', 'sleep', 'ga'],
 ['call', 'alter', 'ok'],
 ['say',
  'like',
  'dat',
  'dun',
  'buy',
  'ericsson',
  'oso',
  'cannot',
  'oredi',
  'lar'],
 ['enter',
  'cabin',
  'pa',
  'said',
  'happi',
  'day',
  'boss',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invit',
  'apart',
  'went'],
 ['aight', 'yo', 'dat', 'straight', 'dogg'],
 ['pleas',
  'give',
  'us',
  'connect',
  'today',
  'lt',
  'decim',
  'gt',
  'refund',
  'bill'],
 ['shoot', 'big', 'load', 'get', 'readi'],
 ['bruv', 'hope', 'great', 'break', 'reward', 'semest'],
 ['home', 'alway', 'chat'],
 ['good', 'studi', 'well'],
 ['yup', 'noe', 'leh'],
 ['sound', 'great', 'home'],
 ['final', 'match', 'head', 'toward', 'draw', 'predict'],
 ['tire', 'slept', 'well', 'past', 'night'],
 ['easi', 'ah', 'sen', 'got', 'select', 'mean', 'good'],
 ['take', 'exam', 'march'],
 ['yeah',
  'think',
  'use',
  'gt',
  'atm',
  'regist',
  'sure',
  'anyway',
  'help',
  'let',
  'know',
  'sure',
  'readi'],
 ['ok', 'prob', 'take', 'ur', 'time'],
 ['os',
  'call',
  'ubandu',
  'run',
  'without',
  'instal',
  'hard',
  'disk',
  'use',
  'os',
  'copi',
  'import',
  'file',
  'system',
  'give',
  'repair',
  'shop'],
 ['sorri', 'call', 'later'],
 ['say',
  'leh',
  'cours',
  'noth',
  'happen',
  'lar',
  'say',
  'romant',
  'ju',
  'bit',
  'lor',
  'thk',
  'nite',
  'sceneri',
  'nice',
  'leh'],
 ['new',
  'mobil',
  'must',
  'go',
  'txt',
  'nokia',
  'collect',
  'today',
  'www',
  'tc',
  'biz',
  'optout',
  'gbp',
  'mtmsg'],
 ['would', 'realli', 'appreci', 'call', 'need', 'someon', 'talk'],
 ['meet',
  'ur',
  'dream',
  'partner',
  'soon',
  'ur',
  'career',
  'flyng',
  'start',
  'find',
  'free',
  'txt',
  'horo',
  'follow',
  'ur',
  'star',
  'sign',
  'horo',
  'ari'],
 ['hey', 'compani', 'elama', 'po', 'mudyadhu'],
 ['life',
  'strict',
  'teacher',
  'bcoz',
  'teacher',
  'teach',
  'lesson',
  'amp',
  'conduct',

In [59]:
import gensim

In [60]:
## lets train Word2vec from scratch
model=gensim.models.Word2Vec(words)

In [61]:
# to get all vocabulary
model.wv.index_to_key

['call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'day',
 'ok',
 'free',
 'know',
 'love',
 'like',
 'time',
 'good',
 'want',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'one',
 'today',
 'take',
 'stop',
 'see',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'tell',
 'still',
 'mobil',
 'back',
 'da',
 'dont',
 'make',
 'phone',
 'pleas',
 'week',
 'hi',
 'say',
 'new',
 'work',
 'later',
 'pl',
 'hope',
 'miss',
 'ask',
 'co',
 'msg',
 'min',
 'meet',
 'dear',
 'night',
 'messag',
 'happi',
 'wait',
 'well',
 'give',
 'thing',
 'tri',
 'much',
 'great',
 'oh',
 'claim',
 'wat',
 'hey',
 'number',
 'thank',
 'friend',
 'way',
 'ye',
 'www',
 'let',
 'prize',
 'feel',
 'right',
 'even',
 'tomorrow',
 'win',
 'pick',
 'alreadi',
 'tone',
 'care',
 'said',
 'cash',
 'im',
 'amp',
 'leav',
 'yeah',
 'realli',
 'babe',
 'find',
 'life',
 'morn',
 'sleep',
 'last',
 'keep',
 'servic',
 'year',
 'uk',
 'nokia',
 'sure',
 'would',
 'buy',
 'anyth',
 'com',
 'use',
 'contact',
 'start',
 'also',
 'lol',
 'everi',
 'wish',
 'urgent',
 'look',
 'smile',
 'sent',
 'end',
 'show',
 'someth',
 'watch',
 'award',
 'gud',
 'us',
 'finish',
 'cant',
 'place',
 'box',
 'first',
 'help',
 'person',
 'guy',
 'someon',
 'special',
 'chat',
 'went',
 'nice',
 'next',
 'tonight',
 'custom',
 'late',
 'talk',
 'soon',
 'word',
 'around',
 'collect',
 'money',
 'could',
 'mani',
 'name',
 'per',
 'ya',
 'plan',
 'sm',
 'alway',
 'gonna',
 'wan',
 'live',
 'minut',
 'lot',
 'check',
 'shop',
 'pm',
 'dun',
 'st',
 'told',
 'mean',
 'hello',
 'heart',
 'girl',
 'fine',
 'month',
 'hour',
 'may',
 'haha',
 'guarante',
 'peopl',
 'reach',
 'best',
 'th',
 'thk',
 'happen',
 'yet',
 'offer',
 'done',
 'god',
 'ppm',
 'thought',
 'play',
 'cost',
 'fuck',
 'line',
 'holiday',
 'class',
 'stuff',
 'bit',
 'man',
 'car',
 'lunch',
 'receiv',
 'enjoy',
 'ill',
 'hous',
 'draw',
 'wk',
 'job',
 'never',
 'mayb',
 'eat',
 'problem',
 'cs',
 'worri',
 'mind',
 'readi',
 'account',
 'hr',
 'better',
 'cool',
 'that',
 'yup',
 'dat',
 'guess',
 'drive',
 'long',
 'rington',
 'pay',
 'date',
 'pobox',
 'rate',
 'quit',
 'game',
 'boy',
 'weekend',
 'chanc',
 'luv',
 'real',
 'half',
 'wonder',
 'latest',
 'world',
 'bring',
 'book',
 'sir',
 'bt',
 'po',
 'yo',
 'room',
 'pic',
 'voucher',
 'noth',
 'wanna',
 'sweet',
 'camera',
 'lar',
 'shit',
 'big',
 'liao',
 'join',
 'anoth',
 'charg',
 'question',
 'put',
 'kiss',
 'stay',
 'age',
 'landlin',
 'birthday',
 'ah',
 'dinner',
 'select',
 'xxx',
 'land',
 'ever',
 'might',
 'video',
 'ju',
 'rememb',
 'network',
 'speak',
 'actual',
 'anyway',
 'hear',
 'wont',
 'appli',
 'probabl',
 'orang',
 'two',
 'babi',
 'thanx',
 'tv',
 'dream',
 'aight',
 'chang',
 'hurt',
 'bed',
 'pa',
 'di',
 'run',
 'nd',
 'fun',
 'earli',
 'final',
 'point',
 'princess',
 'bad',
 'den',
 'offic',
 'sat',
 'shall',
 'nite',
 'answer',
 'forgot',
 'part',
 'left',
 'dunno',
 'made',
 'gift',
 'wake',
 'walk',
 'easi',
 'pain',
 'code',
 'dad',
 'wife',
 'true',
 'didnt',
 'everyth',
 'face',
 'sound',
 'leh',
 'littl',
 'mail',
 'xx',
 'frnd',
 'bu',
 'mate',
 'town',
 'bore',
 'detail',
 'yr',
 'school',
 'movi',
 'afternoon',
 'pound',
 'enough',
 'await',
 'poli',
 'post',
 'read',
 'lose',
 'tmr',
 'without',
 'entri',
 'import',
 'hav',
 'xma',
 'sexi',
 'must',
 'test',
 'price',
 'okay',
 'came',
 'sinc',
 'decid',
 'credit',
 'valid',
 'though',
 'wif',
 'drink',
 'wot',
 'abl',
 'smoke',
 'til',
 'abt',
 'close',
 'mob',
 'lesson',
 'colour',
 'set',
 'goe',
 'plu',
 'away',
 'de',
 'plz',
 'music',
 'decim',
 'bath',
 'order',
 'enter',
 'juz',
 'wen',
 'updat',
 'drop',
 'attempt',
 'beauti',
 'dude',
 'weekli',
 'hand',
 'top',
 'busi',
 'els',
 'havent',
 'hair',
 'doubl',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'onlin',
 'friendship',
 'optout',
 'head',
 'oso',
 'id',
 'coz',
 'haf',
 'food',
 'trip',
 'invit',
 'net',
 'famili',
 'sch',
 'listen',
 'either',
 'club',
 'hot',
 'ring',
 'hold',
 'gr',
 'open',
 'player',
 'inform',
 'address',
 'deliveri',
 'ard',
 'nation',
 'search',
 'sad',
 'togeth',
 'sae',
 'tot',
 'suit',
 'mth',
 'full',
 'wid',
 'stori',
 'touch',
 'si',
 'believ',
 'complet',
 'nt',
 'caus',
 'bonu',
 'second',
 'mom',
 'http',
 'brother',
 'murder',
 'email',
 'train',
 'mum',
 'eve',
 'huh',
 'reason',
 'chikku',
 'row',
 'oki',
 'die',
 'noe',
 'studi',
 'content',
 'match',
 'old',
 'forget',
 'info',
 'anyon',
 'rite',
 'pub',
 'simpl',
 'unsubscrib',
 'park',
 'wil',
 'break',
 'awesom',
 'parent',
 'everyon',
 'dog',
 'expir',
 'privat',
 'took',
 'congrat',
 'tomo',
 'fri',
 'aft',
 'news',
 'hl',
 'treat',
 'auction',
 'sell',
 'laugh',
 'neva',
 'mine',
 'opt',
 'gd',
 'current',
 'valentin',
 'sister',
 'card',
 'sort',
 'choos',
 'angri',
 'reveal',
 'compani',
 'tc',
 'fanci',
 'statement',
 'prob',
 'download',
 'move',
 'tho',
 'valu',
 'caller',
 'avail',
 'alon',
 'understand',
 'gal',
 'knw',
 'sun',
 'whatev',
 'visit',
 'forward',
 'colleg',
 'found',
 'worth',
 'carlo',
 'bank',
 'what',
 'type',
 'ticket',
 'lucki',
 'pass',
 'seem',
 'joke',
 'how',
 'surpris',
 'parti',
 'sit',
 'fast',
 'sub',
 'outsid',
 'nyt',
 'kind',
 'welcom',
 'bout',
 'mobileupd',
 'return',
 'fone',
 'far',
 'anytim',
 'congratul',
 'secret',
 'gbp',
 'exam',
 'bill',
 'ga',
 'rs',
 'boytoy',
 'log',
 'hard',
 'ltd',
 'ni',
 'identifi',
 'uncl',
 'friday',
 'hit',
 'gone',
 'oper',
 'save',
 'song',
 'usual',
 'saturday',
 'smth',
 'ha',
 'winner',
 'tht',
 'chennai',
 'least',
 'wrong',
 'drug',
 'clean',
 'sea',
 'pretti',
 'nope',
 'term',
 'cum',
 'remov',
 'differ',
 'ad',
 'project',
 'interest',
 'light',
 'tel',
 'case',
 'oredi',
 'goodmorn',
 'darlin',
 'mrng',
 'wit',
 'quiz',
 'mu',
 'rain',
 'follow',
 'cut',
 'camcord',
 'confirm',
 'crazi',
 'support',
 'earlier',
 'snow',
 'kid',
 'savamob',
 'frm',
 'scream',
 'suppos',
 'ten',
 'rock',
 'jay',
 'blue',
 'unlimit',
 'cd',
 'fix',
 'fr',
 'meant',
 'cours',
 'spend',
 'tire',
 'hmm',
 'comput',
 'correct',
 'whole',
 'hungri',
 'wq',
 'sunday',
 'freemsg',
 'wkli',
 'father',
 'fren',
 'john',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'store',
 'eye',
 'sex',
 'paper',
 'area',
 'yar',
 'marri',
 'redeem',
 'un',
 'within',
 'fight',
 'sk',
 'india',
 'ass',
 'coupl',
 'motorola',
 'moment',
 'ago',
 'figur',
 'christma',
 'lost',
 'normal',
 'bslvyl',
 'stupid',
 'singl',
 'dnt',
 'side',
 'march',
 'balanc',
 'mr',
 'hmmm',
 'joy',
 'wine',
 'pray',
 'activ',
 'felt',
 'mah',
 'shower',
 'load',
 'hee',
 'etc',
 'almost',
 'catch',
 'turn',
 'eh',
 'promis',
 'reward',
 'press',
 'difficult',
 'grin',
 'fill',
 'heard',
 'photo',
 'extra',
 'ugh',
 'an',
 'xy',
 'darren',
 'gym',
 'remind',
 'max',
 'ladi',
 'ipod',
 'rent',
 'doin',
 'rental',
 'slow',
 'seen',
 'met',
 'ish',
 'via',
 'ge',
 'swing',
 'disturb',
 'laptop',
 'teach',
 'bcoz',
 'semest',
 'connect',
 'deal',
 'safe',
 'sometim',
 'direct',
 'askd',
 'stand',
 'gotta',
 'complimentari',
 'red',
 'ac',
 'wow',
 'hospit',
 'crave',
 'cheer',
 'comp',
 'polic',
 'slowli',
 'fact',
 'fantasi',
 'nobodi',
 'cancel',
 'convey',
 'truth',
 'asap',
 'whenev',
 'fall',
 'possibl',
 'subscrib',
 'idea',
 'ts',
 'noon',
 'door',
 'warm',
 'blood',
 'member',
 'silent',
 'monday',
 'ldn',
 'yep',
 'share',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebodi',
 'hmv',
 'wana',
 'lover',
 'expect',
 'road',
 'regist',
 'kate',
 'orchard',
 'muz',
 'lovabl',
 'txting',
 'page',
 'loan',
 'includ',
 'rpli',
 'abiola',
 'comin',
 'eg',
 'link',
 'wap',
 'copi',
 'request',
 'usf',
 'std',
 'empti',
 'med',
 'cook',
 'excus',
 'hw',
 'cover',
 'write',
 'bb',
 'energi',
 'doctor',
 'digit',
 'regard',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwis',
 'poor',
 'wed',
 'gettin',
 'bag',
 'getz',
 'summer',
 'glad',
 'fantast',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'across',
 'children',
 'less',
 'opinion',
 'near',
 'water',
 'style',
 'wc',
 'mm',
 'mistak',
 'woke',
 'rakhesh',
 'custcar',
 'access',
 'immedi',
 'record',
 'merri',
 'somewher',
 'tonit',
 'deep',
 'admir',
 'kick',
 'street',
 'sign',
 'trust',
 'wast',
 'soni',
 'del',
 'quot',
 'apart',
 'men',
 'gave',
 'repres',
 'il',
 'recent',
 'short',
 'forev',
 'situat',
 'oop',
 'sick',
 'england',
 'bless',
 'callertun',
 'nah',
 'cup',
 'la',
 'tear',
 'sofa',
 'colleagu',
 'flag',
 'thinkin',
 'list',
 'excel',
 'arriv',
 'natur',
 'total',
 'moral',
 'other',
 'mode',
 'mon',
 'deliv',
 'hiya',
 'wear',
 'mo',
 'iam',
 'gay',
 'greet',
 'mid',
 'user',
 'tampa',
 'chariti',
 'comuk',
 'bid',
 'norm',
 'add',
 'bold',
 'pc',
 'hurri',
 'hotel',
 'self',
 'meh',
 'depend',
 'result',
 'kinda',
 'voic',
 'logo',
 'none',
 'al',
 'refer',
 'bluetooth',
 'basic',
 'urself',
 'round',
 'rcvd',
 'cake',
 'power',
 'accept',
 'sport',
 'rose',
 'teas',
 'unless',
 'definit',
 'ldew',
 'goodnight',
 'flirt',
 'appreci',
 'ive',
 'mrt',
 'dead',
 'especi',
 'lift',
 'doesnt',
 'becom',
 'lect',
 'lazi',
 'sunshin',
 'app',
 'flight',
 'boss',
 'coffe',
 'password',
 'ip',
 'bx',
 'ice',
 'mark',
 'serious',
 'issu',
 'mood',
 'pix',
 'manag',
 'er',
 'wednesday',
 'insid',
 'respons',
 'south',
 'vl',
 'honey',
 'cute',
 'black',
 'process',
 'miracl',
 'medic',
 'travel',
 'moon',
 'omg',
 'slave',
 'space',
 'librari',
 'student',
 'bedroom',
 'tuesday',
 'longer',
 'offici',
 'alex',
 'futur',
 'euro',
 'ar',
 'present',
 'daddi',
 'workin',
 ...]

In [62]:
model.corpus_count
# vocabulary size

5564

In [63]:
model.epochs

5

In [64]:
model.wv.similar_by_word('good')

[('day', 0.9995504021644592),
 ('said', 0.9995320439338684),
 ('amp', 0.9995275139808655),
 ('feel', 0.9995059370994568),
 ('hope', 0.9994961023330688),
 ('like', 0.9994935393333435),
 ('dont', 0.9994854927062988),
 ('make', 0.9994717240333557),
 ('much', 0.9994677901268005),
 ('leav', 0.9994635581970215)]

In [65]:
model.wv['good'].shape

(100,)

In [66]:
words[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [67]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    sent = [word for word in doc if word in model.wv.index_to_key]
    if sent:
        return np.mean([model.wv[word] for word in sent], axis=0)
    else:
        # Return a zero vector if no in-vocabulary words are found
        return np.zeros(model.wv.vector_size)

In [68]:
from tqdm import tqdm

In [69]:
# apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|██████████| 5564/5564 [00:01<00:00, 4444.18it/s]

In [70]:
X[0].shape

(100,)

In [71]:
len(X)

5564

In [72]:
## independent feature
X_new=np.array(X)

In [73]:
X_new.shape

(5564, 100)

In [74]:
## dependent feature
y
y.shape

(5572,)

In [75]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']) if i<1]

[[0, '', 'What you doing?how are you?'],
 [0, '', 'Where @'],
 [0, '', '645'],
 [0, '', 'Can a not?'],
 [0, '', ':) '],
 [0, '', 'What you doing?how are you?'],
 [0, '', ':( but your not here....'],
 [0, '', ':-) :-)']]

In [76]:
## you can see shape of x and y are not same because we mention there should be only a to z in regex so, it removes above 8 records
## we need to change y
y=messages[list(map(lambda x:len(x)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0].values.astype(int)

In [77]:
y.shape

(5564,)

In [78]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], shape=(5564,))

In [79]:
## i need to make X[0],X[1],.. as rows in dataframe
df_list = []
for i in range(0,len(X)):
  df_list.append(pd.DataFrame(X[i].reshape(1,-1)))
df = pd.concat(df_list, ignore_index=True)

In [80]:
## why we reshaped it
X[0].shape # 100 rows 1 col but we need 100 col 1 row
X[0].reshape(1,-1).shape

(1, 100)

In [81]:
df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.126219,0.211480,0.093994,-0.077473,0.073083,-0.417712,0.056784,0.487187,-0.095477,-0.192208,...,0.368990,0.096796,0.027680,0.117425,0.423442,0.296432,0.213987,-0.212474,0.114161,-0.033700
1,-0.128258,0.207894,0.087851,-0.073921,0.067530,-0.402821,0.060209,0.465683,-0.093517,-0.182276,...,0.351229,0.094561,0.023843,0.106476,0.405507,0.288272,0.207788,-0.198678,0.114122,-0.030076
2,-0.138387,0.236864,0.101554,-0.083390,0.069801,-0.462853,0.060805,0.544962,-0.103608,-0.216436,...,0.408946,0.103610,0.028836,0.137298,0.476296,0.323311,0.231150,-0.233118,0.132838,-0.027646
3,-0.181256,0.304532,0.130211,-0.119892,0.105113,-0.590048,0.086759,0.686358,-0.129882,-0.264797,...,0.521936,0.138900,0.032486,0.159697,0.599618,0.415249,0.302874,-0.296801,0.162487,-0.053321
4,-0.120411,0.204996,0.088790,-0.076967,0.069581,-0.385731,0.053395,0.456917,-0.088963,-0.174282,...,0.347938,0.090741,0.021292,0.108367,0.401471,0.277736,0.203566,-0.194504,0.107168,-0.036853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5559,-0.165500,0.282852,0.117138,-0.100313,0.080636,-0.532433,0.065166,0.638289,-0.126813,-0.245493,...,0.475807,0.114625,0.035672,0.160720,0.554155,0.371078,0.267849,-0.272802,0.147620,-0.027788
5560,-0.171357,0.283543,0.122991,-0.097970,0.100255,-0.550254,0.084090,0.643460,-0.133405,-0.249134,...,0.486619,0.127680,0.035468,0.145296,0.555771,0.385738,0.281307,-0.280385,0.149733,-0.045251
5561,-0.033334,0.064093,0.030097,-0.018505,0.020180,-0.126018,0.016509,0.154422,-0.026903,-0.054235,...,0.107943,0.033920,0.011271,0.041366,0.133616,0.080153,0.066558,-0.069855,0.033590,-0.003451
5562,-0.142413,0.232892,0.101419,-0.087762,0.074286,-0.455886,0.061801,0.533940,-0.104702,-0.210583,...,0.403240,0.103626,0.029947,0.125935,0.466206,0.321629,0.227643,-0.230283,0.129609,-0.033074
5563,-0.144009,0.230666,0.099850,-0.079251,0.071715,-0.444630,0.057724,0.515641,-0.107760,-0.209720,...,0.399099,0.108429,0.021922,0.125041,0.454368,0.311759,0.222613,-0.229270,0.131517,-0.033424

In [82]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.126219,0.211480,0.093994,-0.077473,0.073083,-0.417712,0.056784,0.487187,-0.095477,-0.192208,...,0.368990,0.096796,0.027680,0.117425,0.423442,0.296432,0.213987,-0.212474,0.114161,-0.033700
1,-0.128258,0.207894,0.087851,-0.073921,0.067530,-0.402821,0.060209,0.465683,-0.093517,-0.182276,...,0.351229,0.094561,0.023843,0.106476,0.405507,0.288272,0.207788,-0.198678,0.114122,-0.030076
2,-0.138387,0.236864,0.101554,-0.083390,0.069801,-0.462853,0.060805,0.544962,-0.103608,-0.216436,...,0.408946,0.103610,0.028836,0.137298,0.476296,0.323311,0.231150,-0.233118,0.132838,-0.027646
3,-0.181256,0.304532,0.130211,-0.119892,0.105113,-0.590048,0.086759,0.686358,-0.129882,-0.264797,...,0.521936,0.138900,0.032486,0.159697,0.599618,0.415249,0.302874,-0.296801,0.162487,-0.053321
4,-0.120411,0.204996,0.088790,-0.076967,0.069581,-0.385731,0.053395,0.456917,-0.088963,-0.174282,...,0.347938,0.090741,0.021292,0.108367,0.401471,0.277736,0.203566,-0.194504,0.107168,-0.036853

In [83]:
## independent feature
X=df

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [85]:
X_train.shape

(4451, 100)

In [86]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [87]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [88]:
## actually above train work without any issue , because we already removed null values before (in avgword2vec)
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [89]:
y_pred=classifier.predict(X_test)

In [90]:
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, ..., 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], shape=(1113,))

In [91]:
from sklearn.metrics import accuracy_score,classification_report

In [92]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.9658580413297394

In [93]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.80      0.86       143
           1       0.97      0.99      0.98       970

    accuracy                           0.97      1113
   macro avg       0.95      0.90      0.92      1113
weighted avg       0.97      0.97      0.96      1113

***Kindle Review -- Sentimental Analysis***

In [94]:
import pandas as pd
df=pd.read_csv('kindle_review.csv')

In [95]:
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [96]:
## so many unnecessary columns i.e features
## reduce them
df=df[['reviewText','rating']]

In [97]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

**Preprocessing and Cleaning**

In [98]:
## Preprocessing and Cleaning
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [99]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [100]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [101]:
## balanced dataset

In [102]:
# 1 means positive 0 means negative
df['rating']=df['rating'].apply(lambda x:1 if x>3 else 0)

In [103]:
df['rating'].value_counts()

rating
0    6000
1    6000
Name: count, dtype: int64

In [104]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       0
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       0
3  Aggie is Angela Lansbury who carries pocketboo...       0
4  I did not expect this type of book to be in li...       1

In [105]:
## we are going to remove special chars,utls,html tags ,stopwords, remove any additional spaces
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from bs4 import BeautifulSoup
import re

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [106]:
## Removing special characters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\dheer\AppData\Local\Temp\ipykernel_3924\3853035056.py:8: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())

In [107]:
df.head()

                                          reviewText  rating
0  Jace Rankin may short hes nothing mess man hau...       0
1  Great short read I didnt want put I read one s...       1
2  Ill start saying first four books I wasnt expe...       0
3  Aggie Angela Lansbury carries pocketbooks inst...       0
4  I expect type book library pleased find price ...       1

In [108]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer

In [109]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dheer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [110]:
lemmatizer=WordNetLemmatizer()

In [111]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [112]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

In [113]:
df.head()

                                          reviewText  rating
0  Jace Rankin may short he nothing mess man haul...       0
1  Great short read I didnt want put I read one s...       1
2  Ill start saying first four book I wasnt expec...       0
3  Aggie Angela Lansbury carry pocketbook instead...       0
4  I expect type book library pleased find price ...       1

In [114]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [115]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [116]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [117]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [118]:
X_train_bow.shape

(9600, 37028)

In [119]:
X_train_tfidf.shape

(9600, 37028)

In [120]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [121]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [122]:
c=confusion_matrix(y_test,y_pred_bow)
print(c)

[[901 271]
 [585 643]]

In [123]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.6433333333333333

In [124]:
confusion_matrix(y_test,y_pred_tfidf)

array([[942, 230],
       [749, 479]])

In [125]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.5920833333333333

let's try to change the rating

In [126]:
import pandas as pd
df1=pd.read_csv('kindle_review.csv')
df1=df1[['reviewText','rating']]
df1.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [127]:
df1['rating']=df1['rating'].apply(lambda x:0 if x<3 else 1)
df1['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [128]:
## Removing special characters
df1['reviewText']=df1['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df1['reviewText']=df1['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df1['reviewText']=df1['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df1['reviewText']=df1['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df1['reviewText']=df1['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\dheer\AppData\Local\Temp\ipykernel_3924\1603215674.py:8: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df1['reviewText']=df1['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())

In [129]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])
df1['reviewText']=df1['reviewText'].apply(lambda x:lemmatize_words(x))

In [130]:
df1.head()

                                          reviewText  rating
0  Jace Rankin may short he nothing mess man haul...       1
1  Great short read I didnt want put I read one s...       1
2  Ill start saying first four book I wasnt expec...       1
3  Aggie Angela Lansbury carry pocketbook instead...       1
4  I expect type book library pleased find price ...       1

In [131]:
df1.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [132]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df1['reviewText'],df1['rating'],test_size=0.20)

In [133]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [134]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_bow=nb_model_bow.predict(X_test_bow)
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [135]:
c=confusion_matrix(y_test,y_pred_bow)
print(c)

[[462 340]
 [942 656]]

In [136]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.4658333333333333

In [137]:
confusion_matrix(y_test,y_pred_tfidf)

array([[459, 343],
       [938, 660]])

In [138]:
confusion_matrix(y_test,y_pred_tfidf)

array([[459, 343],
       [938, 660]])