use case of pandas:

In [1]:
#A series is a one-dimen

In [4]:
import numpy as np
import pandas as pd

In [5]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [10]:
## Creating multiple series -- dataframe

In [11]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [14]:
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [16]:
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [18]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [21]:
df2["Designation"]=["Doctor","engineer","doctor","Eng."] ## make sure list size == no of labels

In [22]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000        Eng.

In [23]:
df2.drop("Designation")

KeyError: "['Designation'] not found in axis"

In [24]:
df2.drop("Designation",axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    engineer
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000        Eng.

In [26]:
df2.drop("Designation",axis=1,inplace=True)## now it deletes from memory

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [29]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df2[0]

KeyError: 0

In [31]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [32]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [34]:
df2.iloc[3] ## what if labels are a,b,c,d it selects by index 3

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [35]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [36]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
## I only want to see those people whose age is above 30

In [38]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [40]:
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [54]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [55]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [56]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [57]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [58]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [59]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [60]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3) ## atleast 3 non null values should be there in a roe

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [62]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
df ## if inplace==True then only it change

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [64]:
values={'A':0,'B':100,"C":300,"D":400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [65]:
## drop will be row wise and selection will be column wise

In [66]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [67]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [4]:
import numpy as np
import pandas as pd

In [3]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [5]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [8]:
pd.merge(employees,salaries,on="employee_id",how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [9]:
pd.merge(employees,salaries,on="employee_id",how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [10]:
pd.merge(employees,salaries,on="employee_id",how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [11]:
pd.merge(employees,salaries,on="employee_id",how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [12]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [13]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2]) #common column

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [16]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [17]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B1': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [18]:
pd.concat([df1,df2])

    A    B   C   B1
0  A0   B0  C0  NaN
1  A1   B1  C1  NaN
2  A2   B2  C2  NaN
0  A3  NaN  C3   B3
1  A4  NaN  C4   B4
2  A5  NaN  C5   B5

In [19]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [20]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [21]:
df2

   score
2     85
3     90
4     75

In [22]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [23]:
df1.join(df2,how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [24]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [25]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [30]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [27]:
#group by category and cal the sum of sales
cat = df.groupby('Category')
cat

In [28]:
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [32]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [33]:
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [35]:
#Group by multiple columns
cat = df.groupby(["Category",'Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
df['Sales'].mean()
""" Aggregation 
median mean min max count std
"""

np.float64(187.5)

In [38]:
df["Sales"].agg(["mean","median","min","max","count"])

mean      187.5
median    190.0
min       100.0
max       300.0
count       8.0
Name: Sales, dtype: float64

In [39]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    251     17   John
1  2023-01-02       B   West    404     90   Mary
2  2023-01-03       C  North    638     59    Bob
3  2023-01-04       D  South    461     62  Alice
4  2023-01-05       A   East    446     73   John
5  2023-01-06       B   West    765     32   Mary
6  2023-01-07       C  North    120     32    Bob
7  2023-01-08       D  South    406     64  Alice
8  2023-01-09       A   East    198     53   John
9  2023-01-10       B   West    238     25   Mary
10 2023-01-11       C  North    988     73    Bob
11 2023-01-12       D  South    930     33  Alice
12 2023-01-13       A   East    190     16   John
13 2023-01-14       B   West    958     74   Mary
14 2023-01-15       C  North    640     58    Bob
15 2023-01-16       D  South    974     63  Alice
16 2023-01-17       A   East    351     60   John
17 2023-01-18       B   West    970     26   Mary
18 2023-01-19       C  North    972     17    Bob
19 2023-01-20       D  South    475     94  Alice

In [40]:
df["Month"]=df['Date'].dt.month_name()
df

         Date Product Region  Sales  Units    Rep    Month
0  2023-01-01       A   East    251     17   John  January
1  2023-01-02       B   West    404     90   Mary  January
2  2023-01-03       C  North    638     59    Bob  January
3  2023-01-04       D  South    461     62  Alice  January
4  2023-01-05       A   East    446     73   John  January
5  2023-01-06       B   West    765     32   Mary  January
6  2023-01-07       C  North    120     32    Bob  January
7  2023-01-08       D  South    406     64  Alice  January
8  2023-01-09       A   East    198     53   John  January
9  2023-01-10       B   West    238     25   Mary  January
10 2023-01-11       C  North    988     73    Bob  January
11 2023-01-12       D  South    930     33  Alice  January
12 2023-01-13       A   East    190     16   John  January
13 2023-01-14       B   West    958     74   Mary  January
14 2023-01-15       C  North    640     58    Bob  January
15 2023-01-16       D  South    974     63  Alice  January
16 2023-01-17       A   East    351     60   John  January
17 2023-01-18       B   West    970     26   Mary  January
18 2023-01-19       C  North    972     17    Bob  January
19 2023-01-20       D  South    475     94  Alice  January

In [41]:
df['Quarter']='Q'+df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    251     17   John  January      Q1
1  2023-01-02       B   West    404     90   Mary  January      Q1
2  2023-01-03       C  North    638     59    Bob  January      Q1
3  2023-01-04       D  South    461     62  Alice  January      Q1
4  2023-01-05       A   East    446     73   John  January      Q1
5  2023-01-06       B   West    765     32   Mary  January      Q1
6  2023-01-07       C  North    120     32    Bob  January      Q1
7  2023-01-08       D  South    406     64  Alice  January      Q1
8  2023-01-09       A   East    198     53   John  January      Q1
9  2023-01-10       B   West    238     25   Mary  January      Q1
10 2023-01-11       C  North    988     73    Bob  January      Q1
11 2023-01-12       D  South    930     33  Alice  January      Q1
12 2023-01-13       A   East    190     16   John  January      Q1
13 2023-01-14       B   West    958     74   Mary  January      Q1
14 2023-01-15       C  North    640     58    Bob  January      Q1
15 2023-01-16       D  South    974     63  Alice  January      Q1
16 2023-01-17       A   East    351     60   John  January      Q1
17 2023-01-18       B   West    970     26   Mary  January      Q1
18 2023-01-19       C  North    972     17    Bob  January      Q1
19 2023-01-20       D  South    475     94  Alice  January      Q1

In [ ]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product")#mean

Product      A      B      C      D
Region
East     287.2    NaN    NaN    NaN
North      NaN    NaN  671.6    NaN
South      NaN    NaN    NaN  649.2
West       NaN  667.0    NaN    NaN

In [44]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     251.0    NaN    NaN    NaN
North      NaN    NaN  640.0    NaN
South      NaN    NaN    NaN  475.0
West       NaN  765.0    NaN    NaN

In [45]:
pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product")#mean

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     287.2    NaN    NaN    NaN  43.8   NaN   NaN   NaN
North      NaN    NaN  671.6    NaN   NaN   NaN  47.8   NaN
South      NaN    NaN    NaN  649.2   NaN   NaN   NaN  63.2
West       NaN  667.0    NaN    NaN   NaN  49.4   NaN   NaN

In [46]:
pd.pivot_table(df,values=["Sales","Units"],index=["Region","Quarter"],columns="Product")#mean

                Sales                      Units
Product             A      B      C      D     A     B     C     D
Region Quarter
East   Q1       287.2    NaN    NaN    NaN  43.8   NaN   NaN   NaN
North  Q1         NaN    NaN  671.6    NaN   NaN   NaN  47.8   NaN
South  Q1         NaN    NaN    NaN  649.2   NaN   NaN   NaN  63.2
West   Q1         NaN  667.0    NaN    NaN   NaN  49.4   NaN   NaN

In [47]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [3]:
import pandas as pd
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [4]:

df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
df1.shape

(5, 3)

In [6]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [8]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [9]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [10]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [11]:
def square(x):
    return x**2

In [12]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [13]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [14]:
df1['B']=df1['B'].apply(square)

In [15]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500